### ISSUE TITLE
请问 Combined 方式的实验是怎么做的？

### ISSUE THREAD

**Issue by QijinYin** [yjxiong/caffe#100]
你好！

我在你们的首页的Results 里有combined 这一项，请问你们这一项实验是怎么做的？

我看了你们的文档,构造了单独的temporal通道（vgg_16_flow_solver.prototxt）
Networks和Spatial通道（vgg_16_rgb_solver.prototxt）Networks。那Combined模式呢？

是像python的demo.py里说的取平均么？
    # fused prediction (temporal:spatial = 2:1)
    fused_pred = np.array(avg_temporal_pred) \* 2./3 + \
                 np.array(avg_spatial_pred) \* 1./3

谢谢!

**Comment by yjxiong** [comment]
We conduct weighted averaging of the probability scores of the two streams. The weights are set to 1:1.5 (spatial:temporal).

For your information, details of the fusion scheme are described in the arxiv report and the original two-stream CNNs paper.

**Comment by QijinYin** [comment]
Thanks！
