### ISSUE TITLE
where is the python layer?

### ISSUE THREAD

**Issue by kli-casia** [yjxiong/caffe#103]
```
Nov 22, 2015
Now python layer can expose a prefetch() method, which will be run in parallel with network processing.
```

However, I can't find where it is.

Thanks.

**Comment by yjxiong** [comment]
Python layer is a type of layer that can use a Python class for forward and backward calculation. However, the content of the calculation has to be specified by the users in their Python class.

**Comment by yjxiong** [comment]
I am closing this as this is not an issue related to the project. Please feel free to reopen it if you encounter any further problem.
