### ISSUE TITLE
some confused with caffe-action_recog

### ISSUE THREAD

**Issue by hanyamin** [yjxiong/caffe#108]
hi
when I use this caffe and data of ucf_rgb_img (I place this data folder  under the folder of caffe-action_recog) to  train a spatial caffemodel , I use  ./build/tools/caffe train --solver=models/action_recognition/vgg_16_rgb_solver.prototxt  --weights=models/action_recognition/vgg_16_action_rgb_pretrain.caffemodel   to train, but I got following error:

E0914 01:47:57.836210 125500 io.cpp:321] Could not load file ucf101_rgb_img/WallPushups/v_WallPushups_g21_c06
F0914 01:47:57.836704 125500 video_data_layer.cpp:79] Check failed: ReadSegmentRGBToDatum(lines_[lines_id_].first, lines_[lines_id_].second, offsets, new_height, new_width, new_length, &datum, true, name_pattern_.c_str()) 
**\* Check failure stack trace: ***

I want to know where to place the folder of ucf_rgb_img( I have already got this folder )

**Comment by yjxiong** [comment]
It should be put at the place you issue the `caffe` command. Or you can prefix everyline with a absolution path instead.
