### ISSUE TITLE
Check failed: cv_cropped_img.data

### ISSUE THREAD

**Issue by Chuseuiti** [yjxiong/caffe#11]
After running make runtest I get:

[==========] Running 1356 tests from 214 test cases.
[----------] Global test environment set-up.
[----------] 27 tests from ReductionLayerTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] ReductionLayerTest/1.TestAbsSumCoeffAxis1Gradient
[       OK ] ReductionLayerTest/1.TestAbsSumCoeffAxis1Gradient (1 ms)
[ RUN      ] ReductionLayerTest/1.TestSum
[       OK ] ReductionLayerTest/1.TestSum (0 ms)
[ RUN      ] ReductionLayerTest/1.TestMean
[       OK ] ReductionLayerTest/1.TestMean (0 ms)
[ RUN      ] ReductionLayerTest/1.TestAbsSum
[       OK ] ReductionLayerTest/1.TestAbsSum (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumCoeffAxis1
[       OK ] ReductionLayerTest/1.TestSumCoeffAxis1 (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumGradient
[       OK ] ReductionLayerTest/1.TestSumGradient (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumOfSquaresCoeffGradient
[       OK ] ReductionLayerTest/1.TestSumOfSquaresCoeffGradient (1 ms)
[ RUN      ] ReductionLayerTest/1.TestMeanCoeffAxis1
[       OK ] ReductionLayerTest/1.TestMeanCoeffAxis1 (0 ms)
[ RUN      ] ReductionLayerTest/1.TestAbsSumCoeff
[       OK ] ReductionLayerTest/1.TestAbsSumCoeff (0 ms)
[ RUN      ] ReductionLayerTest/1.TestAbsSumCoeffAxis1
[       OK ] ReductionLayerTest/1.TestAbsSumCoeffAxis1 (0 ms)
[ RUN      ] ReductionLayerTest/1.TestMeanCoeffGradient
[       OK ] ReductionLayerTest/1.TestMeanCoeffGradient (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumOfSquaresCoeffAxis1Gradient
[       OK ] ReductionLayerTest/1.TestSumOfSquaresCoeffAxis1Gradient (1 ms)
[ RUN      ] ReductionLayerTest/1.TestSumOfSquaresCoeff
[       OK ] ReductionLayerTest/1.TestSumOfSquaresCoeff (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumCoeff
[       OK ] ReductionLayerTest/1.TestSumCoeff (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSetUpWithAxis1
[       OK ] ReductionLayerTest/1.TestSetUpWithAxis1 (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumOfSquaresGradient
[       OK ] ReductionLayerTest/1.TestSumOfSquaresGradient (0 ms)
[ RUN      ] ReductionLayerTest/1.TestAbsSumGradient
[       OK ] ReductionLayerTest/1.TestAbsSumGradient (1 ms)
[ RUN      ] ReductionLayerTest/1.TestMeanCoeff
[       OK ] ReductionLayerTest/1.TestMeanCoeff (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumCoeffGradient
[       OK ] ReductionLayerTest/1.TestSumCoeffGradient (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumOfSquaresCoeffAxis1
[       OK ] ReductionLayerTest/1.TestSumOfSquaresCoeffAxis1 (0 ms)
[ RUN      ] ReductionLayerTest/1.TestMeanCoeffGradientAxis1
[       OK ] ReductionLayerTest/1.TestMeanCoeffGradientAxis1 (1 ms)
[ RUN      ] ReductionLayerTest/1.TestMeanGradient
[       OK ] ReductionLayerTest/1.TestMeanGradient (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumOfSquares
[       OK ] ReductionLayerTest/1.TestSumOfSquares (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSumCoeffAxis1Gradient
[       OK ] ReductionLayerTest/1.TestSumCoeffAxis1Gradient (1 ms)
[ RUN      ] ReductionLayerTest/1.TestAbsSumCoeffGradient
[       OK ] ReductionLayerTest/1.TestAbsSumCoeffGradient (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSetUpWithAxis2
[       OK ] ReductionLayerTest/1.TestSetUpWithAxis2 (0 ms)
[ RUN      ] ReductionLayerTest/1.TestSetUp
[       OK ] ReductionLayerTest/1.TestSetUp (0 ms)
[----------] 27 tests from ReductionLayerTest/1 (6 ms total)

[----------] 2 tests from EuclideanLossLayerTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] EuclideanLossLayerTest/0.TestForward
[       OK ] EuclideanLossLayerTest/0.TestForward (1 ms)
[ RUN      ] EuclideanLossLayerTest/0.TestGradient
[       OK ] EuclideanLossLayerTest/0.TestGradient (0 ms)
[----------] 2 tests from EuclideanLossLayerTest/0 (1 ms total)

[----------] 12 tests from ReshapeLayerTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] ReshapeLayerTest/2.TestFlattenOutputSizes
[       OK ] ReshapeLayerTest/2.TestFlattenOutputSizes (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestInsertSingletonAxesStart
[       OK ] ReshapeLayerTest/2.TestInsertSingletonAxesStart (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestInsertSingletonAxesMiddle
[       OK ] ReshapeLayerTest/2.TestInsertSingletonAxesMiddle (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestInsertSingletonAxesEnd
[       OK ] ReshapeLayerTest/2.TestInsertSingletonAxesEnd (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestFlattenMiddle
[       OK ] ReshapeLayerTest/2.TestFlattenMiddle (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestForwardAfterReshape
[       OK ] ReshapeLayerTest/2.TestForwardAfterReshape (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestCopyDimensions
[       OK ] ReshapeLayerTest/2.TestCopyDimensions (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestInferenceOfUnspecified
[       OK ] ReshapeLayerTest/2.TestInferenceOfUnspecified (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestInferenceOfUnspecifiedWithStartAxis
[       OK ] ReshapeLayerTest/2.TestInferenceOfUnspecifiedWithStartAxis (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestFlattenValues
[       OK ] ReshapeLayerTest/2.TestFlattenValues (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestForward
[       OK ] ReshapeLayerTest/2.TestForward (0 ms)
[ RUN      ] ReshapeLayerTest/2.TestGradient
[       OK ] ReshapeLayerTest/2.TestGradient (12 ms)
[----------] 12 tests from ReshapeLayerTest/2 (12 ms total)

[----------] 5 tests from Im2colLayerTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] Im2colLayerTest/1.TestForward
[       OK ] Im2colLayerTest/1.TestForward (0 ms)
[ RUN      ] Im2colLayerTest/1.TestRect
[       OK ] Im2colLayerTest/1.TestRect (0 ms)
[ RUN      ] Im2colLayerTest/1.TestGradient
[       OK ] Im2colLayerTest/1.TestGradient (197 ms)
[ RUN      ] Im2colLayerTest/1.TestRectGradient
[       OK ] Im2colLayerTest/1.TestRectGradient (178 ms)
[ RUN      ] Im2colLayerTest/1.TestSetup
[       OK ] Im2colLayerTest/1.TestSetup (0 ms)
[----------] 5 tests from Im2colLayerTest/1 (375 ms total)

[----------] 5 tests from MemoryDataLayerTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] MemoryDataLayerTest/1.AddMatVectorDefaultTransform
F1130 14:00:04.401077 14163 data_transformer.cpp:474] Check failed: cv_cropped_img.data 
**\* Check failure stack trace: ***
    @     0x7fb3f47d6d8d  google::LogMessage::Fail()
    @     0x7fb3f47d8d43  google::LogMessage::SendToLog()
    @     0x7fb3f47d6909  google::LogMessage::Flush()
    @     0x7fb3f47d976e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb3f4e4c285  caffe::DataTransformer<>::Transform()
    @     0x7fb3f4e4f841  caffe::DataTransformer<>::Transform()
    @     0x7fb3f4df428b  caffe::MemoryDataLayer<>::AddMatVector()
    @           0x78b341  caffe::MemoryDataLayerTest_AddMatVectorDefaultTransform_Test<>::TestBody()
    @           0xa9b353  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa9238a  testing::Test::Run()
    @           0xa924d8  testing::TestInfo::Run()
    @           0xa925e5  testing::TestCase::Run()
    @           0xa93938  testing::internal::UnitTestImpl::RunAllTests()
    @           0xa93c13  testing::UnitTest::Run()
    @           0x7006ce  main
    @     0x7fb3ed0b7a40  __libc_start_main
    @           0x702179  _start
Aborted (core dumped)
src/caffe/test/CMakeFiles/runtest.dir/build.make:49: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: **\* [src/caffe/test/CMakeFiles/runtest] Error 134
CMakeFiles/Makefile2:273: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: **\* [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:281: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: **\* [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:216: recipe for target 'runtest' failed
make: **\* [runtest] Error 2

It seems that the problem is related to Opencv, but I have the last version of it. That is why I would like to know if a specific version it is needed.

**Comment by yjxiong** [comment]
Hi!
This is fixed with the latest commit. Please try pull and test again.
Thanks

**Comment by yjxiong** [comment]
Is this problem fixed ? @Chuseuiti 
If so, I will close the issue.
