### ISSUE TITLE
the perfomance improvement of tricks which aviod overfitting

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [yjxiong/caffe#110]
To aviod overfitting, you used the following tricks:
     fix_crop: true 
     multi_scale: true 
     max_distort: 1 
    scale_ratios: [1,.875,.75,.66] 
Those four parameters  are not contained in  the offical caffe . Could you tell me the the perfomance improvement of these tricks ?

**Comment by yjxiong** [comment]
We chose these parameters on the split 1 of UCF101. So we don't have specific improvement numbers.

Meanwhile, you can get these number by switching the options on and off in your experiments. Currently, we don't have the spare resource to run these.
