### ISSUE TITLE
flow_mean and rgb_mean 

### ISSUE THREAD

**Issue by xyyu-callen** [yjxiong/caffe#111]
Hello @yjxiong @wanglimin.
[https://github.com/yjxiong/caffe/blob/action_recog/action_matlab/flow_mean.mat](url)
[https://github.com/yjxiong/caffe/blob/action_recog/action_matlab/rgb_mean.mat](url)

What's the use of these two files?

Best Regards

**Comment by yjxiong** [comment]
These are the mat files storing the mean images of rgb and flow input. They are used in video-level testing.

**Comment by xyyu-callen** [comment]
Thank you for your reply.
How do I understand it?
And why did you do this?
These is what I want to know actually.

Best regards

**Comment by yjxiong** [comment]
As its name suggests, a mean image is used for mean subtraction, which is a standard data preprocessing strategy for CNNs.

I suggest reading through the tutorials provided by the Caffe team for things like why we need a mean image and how to use it. Here are some links that may help

http://caffe.berkeleyvision.org/gathered/examples/imagenet.html
http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb

**Comment by xyyu-callen** [comment]
@yjxiong Thank you very much for your attention, Now I have understood this.

Best Regards
