### ISSUE TITLE
some errors when I run demo.py

### ISSUE THREAD

**Issue by xyyu-callen** [yjxiong/caffe#112]
Hello @yjxiong 

I have two question.
1.  When I run demo.py, I get this error.
   [root@localhost action_python]# python demo.py
   F1009 20:50:41.592368 16580 blob.cpp:455] Check failed: ShapeEquals(proto) shape mismatch (reshape not set)
   **\* Check failure stack trace: ***
   Aborted (core dumped)
2. About testing set
   The ucf-101 dateset is divided into train split and test split.
   For caffe, train split and test split represent traing set and validation set respectively.
   If I want to test this model what should I organize testing data set?
   Sampling all of  ucf101 dataset Randomly or just using the test split?

Best regards

**Comment by yjxiong** [comment]
UCF 101 has 3 fixed splits. One should follow these splits to get the accuracy numbers.

**Comment by xyyu-callen** [comment]
Thank you very much. 
For first problem, I setting kReshape = true, On src/caffe/net.cpp: line 838.Then this error has solved. 
But I don't know whether this is correct. Because I modified the source code.

Regards
