### ISSUE TITLE
mpirun 

### ISSUE THREAD

**Issue by geekvc** [yjxiong/caffe#113]
I followed the usage:
mpirun -np 4 ./install/bin/caffe train --solver=<Your Solver File> [--weights=<Pretrained caffemodel>]
use the commond:
mpirun -np 4 ../../build/tools/caffe train --solver=vgg_16_flow_solver.prototxt --weights=vgg_16_action_flow_pretrain.caffemodel
everything goes well, however, the four processes just run on GPU 0 instead of 0,1,2,3
![image](https://cloud.githubusercontent.com/assets/10766005/19256863/4b49f9ac-8f9d-11e6-8857-711860ee6ca2.png)
in the vgg_16_flow_solver.prototxt   the device_id: [0,1,2,3]
Can you help me figure out what is worng ?
thank you very much!

**Comment by yjxiong** [comment]
Hi @geekvc ,

Sorry for late reply, few things to check here:
1. Is the binary compiled with MPI support? You can use `ldd` to check this.
2. The `mpirun` command, is it from the same version of MPI which is used in the compilation?

**Comment by geekvc** [comment]
Thank you for your reply !
I have changed another version and it worked.
thank you

**Comment by yjxiong** [comment]
Nice to know that. Closing the issue...

**Comment by ghost** [comment]
I met same mistake.Can you tell me what you changed? cuda? @geekvc

**Comment by yjxiong** [comment]
@goonder , please see my comment on Oct 16, 2016.
