### ISSUE TITLE
dilation is not supported

### ISSUE THREAD

**Issue by quietsmile** [yjxiong/caffe#117]
Is there any plan to support dilated convolution?
Thanks

**Comment by yjxiong** [comment]
Sorry, dilated conv is currently not included in this repo. We may add it if someone wills to contribute a PR on this.

**Comment by yjxiong** [comment]
#124

**Comment by yjxiong** [comment]
Closing this as the dilated convolution has been merge to the default branch in #132 .
@quietsmile
