### ISSUE TITLE
Can't find a proper way to extract the features

### ISSUE THREAD

**Issue by livst** [yjxiong/caffe#119]
I've tried to extract the features with the extract_features tool provided in /build/tools/ but it doesn't work as expected. Any solution?

I used the vgg_16_rgb_train_val_fast.prototxt as the network definition. The input was train_rgb_split1.txt.

The problem is that using the extract_features tool one gets 1 single vector for the whole folder. Shouldn't it extract 1 vector for each frame? so in this example, for this input:

ucf101_rgb_img/WallPushups/v_WallPushups_g21_c06 111 98

I should get 111 features vectors. One vector for each frame in the folder. But by using the specified tool, i get only 1 vector.

Thank you for your assistance!
livst

**Comment by livst** [comment]
The same problem occures when using the optical flow network.
I should get a vector for each 20 stacked optical flow images. So, for the above example, i should have got~ 11 feature vectors. But again, i receive only one vector for the whole folder.

Also, by using the same tool to extract the features, without changing anything, i get different values in the extracted vector, when I execute the tool again.

**Comment by livst** [comment]
Am I missing something? Is that vector the features vector for the whole video?

**Comment by yjxiong** [comment]
Use this

https://github.com/yjxiong/caffe/tree/action_recog/action_matlab

or this

https://github.com/yjxiong/caffe/tree/action_recog/action_python

**Comment by livst** [comment]
I tried to use the matlab demo but i get the following error:

Undefined variable "caffe" or class "caffe.reset_all".

Error in demo (line 11)
caffe.reset_all();

**Comment by livst** [comment]
Hi,

I tried to use the matlab demo but i got the following error:

>> demo
Undefined variable "caffe" or class "caffe.reset_all".

Error in demo (line 11)
caffe.reset_all();
 
Any suggestion? Thank you!

**Comment by livst** [comment]
I also tried the action_python demo script, but i get the following error:

action_python/VideoTemporalPrediction.py", line 44, in VideoTemporalPrediction
    img_x = cv2.resize(img_x, dims[1::-1])
/imgwarp.cpp:1968: error: (-215) ssize.area() > 0 in function resize

**Comment by livst** [comment]
I tried the python demo from action_python, but i get the following error:

action_python/VideoTemporalPrediction.py", line 85, in VideoTemporalPrediction
    prediction[:, span] = np.transpose(output[feature_layer])
KeyError: 'fc8-2'

**Comment by livst** [comment]
Did anyone managed to use the script, I couldn't run any of them, every single one has some wrong lines. For example, now i get this error:

action_python/VideoTemporalPrediction.py", line 85, in VideoTemporalPrediction
    prediction[:, span] = np.transpose(output[feature_layer])
ValueError: shape mismatch: value array of shape (101,50) could not be broadcast to indexing result of shape (50,131)

**Comment by livst** [comment]
What doesn't num_samples parameter does in the caffe/action_python/VideoTemporalPrediction.py ?

**Comment by livst** [comment]
Why do the number of frames is limited to 25?

**Comment by yjxiong** [comment]
We extract 25 snippets to establish fair comparison with previous methods. In applications, it is not required to only take 25 snippets.
