### ISSUE TITLE
cannot download flow data

### ISSUE THREAD

**Issue by antran89** [yjxiong/caffe#12]
Hi Mr. Xiong Yuanjun,
I want to report that I cannot download [flow data](http://mmlab.siat.ac.cn/very_deep_two_stream_model/ucf101_flow_img_tvl1_gpu.zip). It failed on the halfway, and I tried many times. I am from NUS, Singapore. Any helps from you guys?
Thanks,

**Comment by wanglimin** [comment]
Hi An Tran,

Our server is not stable. If you really cannot download our flow data, you
could try the following code to extract flow by yourself:

https://github.com/yjxiong/dense_flow

Best,

Limin

On Mon, Dec 7, 2015 at 7:41 AM, An Tran notifications@github.com wrote:

> Hi Mr. Xiong Yuanjun,
> I want to report that I cannot download flow data
> http://mmlab.siat.ac.cn/very_deep_two_stream_model/ucf101_flow_img_tvl1_gpu.zip.
> It failed on the halfway, and I tried many times. I am from NUS, Singapore.
> Any helps from you guys?
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/12.

## 

Limin Wang
Post-doctoral Researcher, CVL, ETH, Zurich
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by antran89** [comment]
Thanks
