### ISSUE TITLE
frame number when training rgb model

### ISSUE THREAD

**Issue by CrossLee1** [yjxiong/caffe#120]
Hi, when training the rgb model, do you use all the frames in a video, or sample frames equally across the video?

Thanks a lot~

**Comment by yjxiong** [comment]
Hi @CrossLee1 ,

For this work (very deep two stream CNN), we randomly sample one snippet from the whole video during each iteration.

Here, one snippet is defined as one RGB frame or 10 continuous flow frames.

**Comment by CrossLee1** [comment]
@yjxiong 
Understood, thanks for your quickly reply~

**Comment by yjxiong** [comment]
No problem. Closing this issue.

And also want to add that this is a good question. 

In our latest state-of-the-art action recognition work, [temporal segment networks (TSN)](https://github.com/yjxiong/temporal-segment-networks), a new snippet sample scheme has led to one of the core contributions to its significant performance gain.
