### ISSUE TITLE
cmake warning and make error

### ISSUE THREAD

**Issue by Xiao-G1023** [yjxiong/caffe#128]
Hi Prof. Xiong!
Your work is interesting, but I meet some problems when I reproduce it under your guidance. When I do `cmake .. -DUSE_MPI=ON`, I got the following results with some warnings in the end.

-- ********Caffe Configuration Summary ******
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   unknown
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release

--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF

-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   Snappy            :   Yes (ver. 1.1.0)
--   LevelDB           :   Yes (ver. 1.15)
--   OpenCV            :   Yes (ver. 2.4.12)
--   CUDA              :   Yes (ver. 7.5)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
--   cuDNN             :   Yes

-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.6)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
--   NumPy             :   /usr/local/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.1)

-- Documentaion:
--   Doxygen           :   No
--   config_file       :   

-- Install:
--   Install path      :   /home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/buildinstall

-- Configuring done

CMake Warning at src/caffe/CMakeLists.txt:20 (add_library):
  Cannot generate a safe runtime search path for target caffe because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
CMake Warning at src/caffe/test/CMakeLists.txt:29 (add_executable):
  Cannot generate a safe runtime search path for target test.testbin because
  files in some directories may conflict with libraries in implicit
  directories:
    runtime library [libcudnn.so.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
### ...............(some warnings like this)
-- Generating done
-- Build files have been written to: /home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/build

### If I don't care about these warnings and go on doing `make`, then it goes wrong like this:
.......
[ 66%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/bias_layer.cpp.o
[ 66%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/sigmoid_cross_entropy_loss_layer.cpp.o
[ 66%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/lrn_layer.cpp.o
[ 67%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/log_layer.cpp.o
[ 67%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/slice_layer.cpp.o
[ 69%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/data_layer.cpp.o
[ 69%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_conv_layer.cpp.o
In file included from /home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/include/caffe/util/device_alternate.hpp:40:0,
                 from /home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/include/caffe/common.hpp:34,
                 from /home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/include/caffe/blob.hpp:8,
                 from /home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/include/caffe/filler.hpp:10,
                 from /home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/src/caffe/layers/cudnn_conv_layer.cpp:5:
/home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/include/caffe/util/cudnn.hpp: In instantiation of ‘void caffe::cudnn::createFilterDesc(cudnnFilterStruct**, int, int, int, int) [with Dtype = float; cudnnFilterDescriptor_t = cudnnFilterStruct*]’:
/home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/src/caffe/layers/cudnn_conv_layer.cpp:251:3:   required from ‘void caffe::CuDNNConvolutionLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’
/home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/src/caffe/layers/cudnn_conv_layer.cpp:474:1:   required from here
/home/zhoupeipei/action-code/2016ECCV_TSN_master/lib/caffe-action/include/caffe/util/cudnn.hpp:94:3: error: too many arguments to function ‘cudnnStatus_t cudnnSetFilter4dDescriptor(cudnnFilterDescriptor_t, cudnnDataType_t, int, int, int, int)’
......

## I have config the OpenMPI `--with-cuda`. The mpi version is 1.8.8 and I test as follows: 
2016ECCV_TSN_master/lib/caffe-action$ ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
mca:mpi:base:param:mpi_built_with_cuda_support:value:true

 I am not sure if the `make` errors result from the wrong cudnn version or other reasons.
Thanks  and looking for your reply.  Best wishes!

**Comment by yjxiong** [comment]
Seems you have an incorrect cuDNN version. This codebase now depends on cuDNN v5.

**Comment by Xiao-G1023** [comment]
Thanks Prof. Xiong! In the next step, I will update the cuDNN version.

**Comment by Xiao-G1023** [comment]
Once I update the cuDNN to cuDNN v5, the warnings during `cmake` and errors during `make` disappear! Thank you very much!

**Comment by yjxiong** [comment]
@Xiao-G1023. Good to know. Closing this issues as it's resolved.
