### ISSUE TITLE
can I use mkl ?

### ISSUE THREAD

**Issue by Xiao-G1023** [yjxiong/caffe#129]
Hi,

can I use mkl ? and how can I select mkl when cmake

thanks

**Comment by yjxiong** [comment]
Yes you can. 
The BLAS choices can be found via the CMake GUI `ccmake`.

**Comment by Xiao-G1023** [comment]
thank you very much,just like you said,I can select mkl via cmake-gui,But ,when I select USE_MPI in the cmake-gui , in the cmake-gui ,there are some wrong:

MPI_LIBRARY-NOTFOUND
MPI_EXTRA_LIBRARY-NOTFOUND

and the information after configuire :


       Boost version: 1.54.0
Found the following Boost libraries:
  system
  thread
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
Found PROTOBUF Compiler: /usr/bin/protoc
Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
CUDA detected: 7.5
Found cuDNN (include: /usr/local/include, library: /usr/local/lib/libcudnn.so)
Added CUDA NVCC flags for: sm_37
OpenCV found (/usr/local/share/OpenCV)
Found MKL: /opt/intel/mkl/include  
Found MKL (include: /opt/intel/mkl/include, lib: /opt/intel/mkl/lib/intel64/libmkl_rt.so
Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.6", minimum required is "2.7") 
Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7") 
Found NumPy: /usr/local/lib/python2.7/dist-packages/numpy/core/include (found suitable version "1.11.2", minimum required is "1.7.1") 
NumPy ver. 1.11.2 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
Could NOT find Boost
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Unable to determine MPI from MPI driver /usr/local/bin/mpicc
Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
Unable to determine MPI from MPI driver /usr/local/bin/mpicxx
Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
Python interface is disabled or not all required dependecies found. Building without it...
Could NOT find Git (missing:  GIT_EXECUTABLE) 

******************* Caffe Configuration Summary *******************
General:
  Version           :   <TODO> (Caffe doesn't declare its version in headers)
  Git               :   unknown
  System            :   Linux
  C++ compiler      :   /usr/bin/c++
  Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
  Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
  Build type        :   Release

  BUILD_SHARED_LIBS :   ON
  BUILD_python      :   ON
  BUILD_matlab      :   OFF
  BUILD_docs        :   ON
  CPU_ONLY          :   OFF

Dependencies:
  BLAS              :   Yes (MKL)
  Boost             :   Yes (ver. 1.54)
  glog              :   Yes
  gflags            :   Yes
  protobuf          :   Yes (ver. 2.5.0)
  lmdb              :   Yes (ver. 0.9.10)
  Snappy            :   Yes (ver. 1.1.0)
  LevelDB           :   Yes (ver. 1.15)
  OpenCV            :   Yes (ver. 3.0.0)
  CUDA              :   Yes (ver. 7.5)

NVIDIA CUDA:
  Target GPU(s)     :   Auto
  GPU arch(s)       :   sm_37
  cuDNN             :   Yes

Documentaion:
  Doxygen           :   No
  config_file       :   

Install:
  Install path      :   /home/xs/deep-learning/TSN/lib/caffe-action/build/install

Configuring done

how can i set the MPI_LIBIRARY and MPI_EXTRA_LIBRARY?

**Comment by yjxiong** [comment]
MPI location can be set by `cmake .. -DUSE_MPI=ON -DMPI_CXX_COMILER=<localtion to mpicxx>`.
