### ISSUE TITLE
Any requirements on format of video frames name?

### ISSUE THREAD

**Issue by antran89** [yjxiong/caffe#13]
Hi @yjxiong,
I tried to finetune the `spatial-VGG-16` network with your prototxt file and your [RGB frames split](https://github.com/yjxiong/caffe/tree/action_recog/examples/action_recognition/dataset_file_examples). However, I met the errors `cannot load file`. I checked that my data is alright with your format `%04.jpg` starting index from 1. (I modified your code  a little bit at https://github.com/yjxiong/caffe/blob/action_recog/src/caffe/util/io.cpp#L316)

```
1211 22:43:31.502714  4785 layer_factory.hpp:74] Creating layer data
I1211 22:43:31.502755  4785 net.cpp:94] Creating Layer data
I1211 22:43:31.502771  4785 net.cpp:413] data -> data
I1211 22:43:31.502806  4785 net.cpp:413] data -> label_local
I1211 22:43:31.502821  4785 net.cpp:158] Setting up data
I1211 22:43:31.503285  4785 video_data_layer.cpp:34] Opening file: train_rgb_split1.txt
I1211 22:43:31.509351  4785 video_data_layer.cpp:50] A total of 9537 videos.
E1211 22:43:31.509426  4785 io.cpp:320] Could not load file /home/tranlaman/Public/data/video/UCF101/WallPushups/v_WallPushups_g21_c06
F1211 22:43:31.509577  4785 video_data_layer.cpp:66] Check failed: ReadSegmentRGBToDatum(lines_[lines_id_].first, lines_[lines_id_].second, offsets, new_height, new_width, new_length, &datum, true) 
*** Check failure stack trace: ***
    @     0x7fc55c4bbdaa  (unknown)
    @     0x7fc55c4bbce4  (unknown)
    @     0x7fc55c4bb6e6  (unknown)
    @     0x7fc55c4be687  (unknown)
    @     0x7fc55c90d8ff  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7fc55c8ed3e5  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fc55c83ad02  caffe::Net<>::Init()
    @     0x7fc55c83c963  caffe::Net<>::Net()
    @     0x7fc55c9241c9  caffe::Solver<>::InitTrainNet()
    @     0x7fc55c92526e  caffe::Solver<>::Init()
    @     0x7fc55c925406  caffe::Solver<>::Solver()
    @           0x417f40  caffe::GetSolver<>()
    @           0x40ff02  train()
    @           0x40e6e6  main
    @     0x7fc55af75ec5  (unknown)
    @           0x40eccb  (unknown)
    @              (nil)  (unknown)
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 4786 on node uCom exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```

Thanks,

**Comment by wanglimin** [comment]
Hi，

It seems the program could not find the image files.

Can you make sure your file follow the format:

sprintf(tmp,"image_%04d.jpg",int(file_id+offset)); string filename_t =
filename + "/" + tmp; Limin

On Fri, Dec 11, 2015 at 4:02 PM, An Tran notifications@github.com wrote:

> Hi @yjxiong https://github.com/yjxiong,
> I tried to finetune the spatial-VGG-16 network with your prototxt file
> and your RGB frames split
> https://githubcom/yjxiong/caffe/tree/action_recog/examples/action_recognition/dataset_file_examples
> However, I met the errors cannot load file I checked that my data is
> alright with your format %04jpg starting index from 1
> 
> 1211 22:43:31502714  4785 layer_factoryhpp:74] Creating layer data
> I1211 22:43:31502755  4785 netcpp:94] Creating Layer data
> I1211 22:43:31502771  4785 netcpp:413] data -> data
> I1211 22:43:31502806  4785 netcpp:413] data -> label_local
> I1211 22:43:31502821  4785 netcpp:158] Setting up data
> I1211 22:43:31503285  4785 video_data_layercpp:34] Opening file: train_rgb_split1txt
> I1211 22:43:31509351  4785 video_data_layercpp:50] A total of 9537 videos
> E1211 22:43:31509426  4785 iocpp:320] Could not load file /home/tranlaman/Public/data/video/UCF101/WallPushups/v_WallPushups_g21_c06
> F1211 22:43:31509577  4785 video_data_layercpp:66] Check failed: ReadSegmentRGBToDatum(lines_[lines_id_]first, lines_[lines_id_]second, offsets, new_height, new_width, new_length, &datum, true)
> **\* Check failure stack trace: ***
>     @     0x7fc55c4bbdaa  (unknown)
>     @     0x7fc55c4bbce4  (unknown)
>     @     0x7fc55c4bb6e6  (unknown)
>     @     0x7fc55c4be687  (unknown)
>     @     0x7fc55c90d8ff  caffe::VideoDataLayer<>::DataLayerSetUp()
>     @     0x7fc55c8ed3e5  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
>     @     0x7fc55c83ad02  caffe::Net<>::Init()
>     @     0x7fc55c83c963  caffe::Net<>::Net()
>     @     0x7fc55c9241c9  caffe::Solver<>::InitTrainNet()
>     @     0x7fc55c92526e  caffe::Solver<>::Init()
>     @     0x7fc55c925406  caffe::Solver<>::Solver()
>     @           0x417f40  caffe::GetSolver<>()
>     @           0x40ff02  train()
>     @           0x40e6e6  main
>     @     0x7fc55af75ec5  (unknown)
>     @           0x40eccb  (unknown)
> 
> ##     @              (nil)  (unknown)
> 
> ## mpirun noticed that process rank 1 with PID 4786 on node uCom exited on signal 6 (Aborted)
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/13.

## 

Limin Wang
Post-doctoral Researcher, CVL, ETH, Zurich
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by antran89** [comment]
Hi @wanglimin,
What is the meaning of `offset` variable? Is it the second column in the [split file](https://github.com/yjxiong/caffe/blob/action_recog/examples/action_recognition/dataset_file_examples/train_rgb_split1.txt).
What is the meaning of the third column?
Thank for your quick reply.

**Comment by wanglimin** [comment]
The second column is the duration of video and the third is the class label
(starting from 0)

Limin

On Fri, Dec 11, 2015 at 4:20 PM, An Tran notifications@github.com wrote:

> Hi @wanglimin https://github.com/wanglimin,
> What is the meaning of offset variable? Is it the second column in the split
> file
> https://github.com/yjxiong/caffe/blob/action_recog/examples/action_recognition/dataset_file_examples/train_rgb_split1.txt
> .
> What is the meaning of the third column?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/13#issuecomment-163961819.

## 

Limin Wang
Post-doctoral Researcher, CVL, ETH, Zurich
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by antran89** [comment]
Thank @wanglimin,
I know what the problem is. The decoding on my machine would generate different length of frames than on the split file. I need to generate the split file again. Thank you anyway. You help me to solve the problem.
