### ISSUE TITLE
python接口的编译

### ISSUE THREAD

**Issue by hiyijian** [yjxiong/caffe#131]
你好，感谢你分享的代码。
我试图使用python接口，发现cmake中关于python的部分似乎被有意删除了。所以添加了相应的编译脚本。由于我只关心测试部分，而非训练，所以我没有开启mpi开关，编译顺利完成。
但在测试时，发现测试结果不对，和训练时的日志完全对不上，结果类似随机，看起来似乎没有正确加载模型。
请问我是否犯了一些明显的错误，如何才能正确的使用python接口进行Test呢？谢谢

**Comment by yjxiong** [comment]
It is not deleted. To compile the Python interfaces, you need a boost version higher than 1.54. 

Please do not modify the CMake scripts unless you know what you are doing.

**Comment by hiyijian** [comment]
我的问题已解决，是我自己的问题。python接口可用。谢谢
