### ISSUE TITLE
Question about params' gradients  sync

### ISSUE THREAD

**Issue by hiyijian** [yjxiong/caffe#134]
hi, @yjxiong ,
  I notice that the params' gradients  are reduced layer by layer at backward phase in your code(net.cpp). Another single thread is responsible for doing actual communication(channel.cpp). In another word, backward computing and gradients communication take place parallelly. Am I right?
  Let's pay attention to operation of all_reduce:  caffe_iallreduce(this->params_[n]->mutable_cpu_diff(),  this->params_[n]->count();  Firstly , The gradients in GPU must to be moved to its host(CPU),  and then reduce with other worker via MPI. At very beiging, I think we might eliminate operation of GPU->CPU, so as to achieve better performance via cuda-aware MPI. So I did it, but it turns out to cost much more time per iteration
  I am not good at CUDA and MPI stuff at all. Can you explain this ? Or is there a way to improve the communication efficiency, since it is the obvious bottleneck of my task according to my careful analysis

**Comment by hiyijian** [comment]
PS: Our device is 4 TITAN X(Pascal)

**Comment by yjxiong** [comment]
Closing as this is not an issue.

**Comment by yjxiong** [comment]
This is expected as OpenMPI poorly implemented its CUDA-aware primitives. Currently, as far as I know the CUDA-aware version of OpenMPI AllReduce op is suboptimal unless you have Tesla series GPUs and Infiniband interconnect.
