### ISSUE TITLE
can not run the debug version of caffe

### ISSUE THREAD

**Issue by gooners1886** [yjxiong/caffe#135]
I open the switch in Makefile.confing:  DEBUG := 1  and recompile the debug version of caffe. But when i run the caffe using gdb with command : 
gdb --args lib/caffe-action/build/install/bin/caffe  train --solver=models/hmdb51/tsn_bn_inception_flow_solver.prototxt --weights=models/bn_inception_flow_init.caffemodel

it outputs: 
Reading symbols from /home/yangyang/code/tsn_all/tsn_b2/lib/caffe-action/build/install/bin/caffe...(no debugging symbols found)...done.
no debugging symbols found  ---- I think this means the debug verison does not run normally. 

How can I deal with this problem?

**Comment by yjxiong** [comment]
First, we use CMake as the build tool. The original MakeFile is just there for legacy use and it is not tested against the latest version.

For your problem, if you use the MakeFile to build the codebase, the binary executable will not be located in `build/install/bin/`, but instead be in places like `build/tools/` or something.
