### ISSUE TITLE
mpirun -np 4 ..., get 7 processes occupy 4 GPUs

### ISSUE THREAD

**Issue by hiyijian** [yjxiong/caffe#136]
hi, stuff
It is as following:
![image](https://cloud.githubusercontent.com/assets/4326958/22056720/68593f6a-dd9c-11e6-95c0-533bc369d0be.png)

Indeed, there are actually 4 **unique** processes. However, I expect 4 processes occupy 4 GPUs respectively, How it comes?

**Comment by yjxiong** [comment]
This is fine. Certain combinations of OpenMPI and CUDA versions will allocate a buffer on the 0-th GPU for efficient communication.

**Comment by hiyijian** [comment]
Thanks
