### ISSUE TITLE
memory optimization

### ISSUE THREAD

**Issue by mengyuanxbox360** [yjxiong/caffe#139]
Dear YJXiong:

I'm using the memory optimization feature in your latest caffe distribution. According to the code, only the split layer gather layer reshape layer and flatten layer has shared data or diff. As we are testing on the resnet50, it saves 1G memory. We mostly use split layer, however, the data is shared for split layer in original caffe setting, how do you save the memory in this situation.  

Thanks a lot

**Comment by yjxiong** [comment]
This is a blog I wrote on the memory optimization. You are more than welcome to read it if you feel interested in how it is done.

http://blog.yjxiong.me/archives/403

Closing this issue as it is not a problem in the codebase.
