### ISSUE TITLE
run training on 1 GPU

### ISSUE THREAD

**Issue by antran89** [yjxiong/caffe#14]
Hi @wanglimin,
I am running your caffe on two GPUs using OpenMPI. However, my workstation has a power problem when running your Caffe on multiple GPUs. My workstation runned for short time and restarted. I have a question for you. Is there any difference on performance, when we are running your Caffe with `np=1` on 1 GPU and the original Caffe.

```
mpirun -np 1 ./install/bin/caffe train --solver=<Your Solver File> [--weights=<Pretrained caffemodel>]
```

Thanks

**Comment by yjxiong** [comment]
There is no synchronization when run with only one process. So basically there is no communication overhead in this situation. You should be able to get comparable or better performance of the original Caffe.

As a side note, to overcome the power shortage, you can lower the application clocks of the GPUs to  limit the maximum power consumption of them.

**Comment by antran89** [comment]
Thanks @yjxiong,
An

**Comment by antran89** [comment]
Thank @yjxiong about your advice on lowering the application clocks. It is really useful.
