### ISSUE TITLE
Memory problems in demo.py

### ISSUE THREAD

**Issue by StOnEGiggity** [yjxiong/caffe#140]
Hi,
  I run demo.py with the spatial model and the temporal model you supported,it occurs one problem like that:F0217 11:09:23.479010  3432 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory.I find the soluation is reducing the banchsize.
  **Does it mean i need to train my own model with lower banchsize and higher iter_size?**,thank you

**Comment by yjxiong** [comment]
That demo.py does not relate to training. You should adjust the training parameters based on the GPU you have.
