### ISSUE TITLE
cudaDeviceSynchronize() in Gather/Scatter layer

### ISSUE THREAD

**Issue by hiyijian** [yjxiong/caffe#141]
hi @yjxiong 

I found that you call "cudaDeviceSynchronize()" in ForwardGPU of Gather or Scatter  layer. Is it necessary and why?

Thanks

**Comment by yjxiong** [comment]
It is necessary as there will be an `MPI_allgather`/`MPI_allscatter` call on GPU memory in another thread. Going without synchronization can potentially lead to data corruption.

**Comment by hiyijian** [comment]
Can you explain it more please ? In which case  there will be an MPI_allgather/MPI_allscatter call on GPU memory in another thread **if there is only one gather layer in network** ? 
Thanks

**Comment by yjxiong** [comment]
All MPI invocations are performed in a separate thread, which operates a task queue to handle the communication requests. Gather/Scatter layers' GPU forward function uses GPU-aware MPI primitives. This is why there is ``MPI_allgather/MPI_allscatter call on GPU memory in another thread"

**Comment by hiyijian** [comment]
Many thanks. 

One more question please : Do you think it is safe to remove "cudaDeviceSynchronize()" if we call MPI API in the same thread via modify "src/util/channel.cpp" ?

We have stwiched the  heaviest comunication task "allreudce" from OpenMPI to [NCCL](https://github.com/NVIDIA/nccl) (yes, we only work with a single node now).  From my best knowledge about your version of caffe,  allreudce during backprop is the only place needs asynchronous communication. Other places like gather/scatter or model/loss synchronization take place in a  synchronous manner. As a result, remove the thead related stuff in "src/util/channel.cpp" may not hurt performance too much. Am I right？

Thanks

**Comment by yjxiong** [comment]
You are free to experiment with any change. Since I haven't had any experiment on your proposed changes, I can not judge by now which will improve or not.

**Comment by hiyijian** [comment]
Thanks
