### ISSUE TITLE
I can't find the function ' caffe.mpi_init()' in the python interface when I run a python script. 

### ISSUE THREAD

**Issue by maochaojie** [yjxiong/caffe#145]
The error is as following:
Traceback (most recent call last):
  File "tools/eval_test.py", line 159, in <module>
    main(args)
  File "tools/eval_test.py", line 70, in main
    caffe.mpi_init()
AttributeError: 'module' object has no attribute 'mpi_init'

Thanks!

**Comment by yjxiong** [comment]
Seems we don't have your script. Can you tell us more details?

**Comment by maochaojie** [comment]
https://github.com/ShuangLI59/person_search/blob/master/tools/eval_test.py

I use this python script when I try to repeat the work of Tong Xiao and Shuang Li('Joint Detection and Identification Feature Learning for Person Search'). They use your caffe version.

**Comment by yjxiong** [comment]
Then you should use this version.

https://github.com/Cysu/caffe/tree/aed38841ae4282d90575186b87c3287620913722

It is modified from our tool but not equivalent.

**Comment by zhanghm01** [comment]
> The error is as following:
> Traceback (most recent call last):
> File "tools/eval_test.py", line 159, in
> main(args)
> File "tools/eval_test.py", line 70, in main
> caffe.mpi_init()
> AttributeError: 'module' object has no attribute 'mpi_init'
> 
> Thanks!

hello!I have the same problem:
 $python tools/demo.py --gpu 0
Traceback (most recent call last):
  File "tools/demo.py", line 114, in <module>
    main(args)
  File "tools/demo.py", line 30, in main
    caffe.mpi_init()
AttributeError: 'module' object has no attribute 'mpi_init'

The caffe version I am using is  in 
https://github.com/Cysu/caffe/tree/aed38841ae4282d90575186b87c3287620913722
How did you finally solve this problem?
Thank you !
