### ISSUE TITLE
编译错误求指导

### ISSUE THREAD

**Issue by JosephChenHub** [yjxiong/caffe#146]
我尝试过openmpi 1.7.5和1.10.1版本，编译时加了--with-cuda，然后编译caffe时出现link error:
Linking CXX executable mnist/convert_mnist_data
/home/zuyao.chen/OpenMPI_1.10.1/lib/libopen-pal.so.13: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/home/zuyao.chen/OpenMPI_1.10.1/lib/libopen-pal.so.13: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/home/zuyao.chen/OpenMPI_1.10.1/lib/libopen-pal.so.13: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
/home/zuyao.chen/OpenMPI_1.10.1/lib/libopen-pal.so.13: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/mnist/convert_mnist_data] Error 1
make[1]: *** [examples/CMakeFiles/convert_mnist_data.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

求指导

**Comment by yjxiong** [comment]
`clGetPlatformIDs@OPENCL_1.0` check OpenCL?

**Comment by JosephChenHub** [comment]
I meet two problems:
1. maybe I solved it ，there is two libOpenCL.so.1 in my service computer,like this:
	libOpenCL.so.1 (libc6,x86-64) => /usr/local/cuda-7.5/lib64/libOpenCL.so.1
	libOpenCL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
when I has installed the OpenMPI 1.10.1, I got an warning "mpirun : /usr/local/cuda-7.5/lib64/libOpenCL.so.1  : no version information available （required by ... libopen-pal.so.13“) ,
then I add "/usr/lib/x86_64-linux-gnu/libOpenCL.so.1" to "MPI_CXX_LIBRARIES", make all OK,but has a warning (/usr/lib/x86_64-linux-gnu/libOpenCL.so.1 maybe hidden by  /usr/local/cuda-7.5/lib64/). 
2. the program is working but accuracy is still 0.1  on cifar10,my model is ResNet32, "BatchNorm" layer is replaced by "BN"

**Comment by GerrieWell** [comment]
Hey . I compile successfully by your approach .But still fail to make runtest. here is my log. 
```shell
/home/wuyong/xy_share/reidPrj/person_search/caffe/build/test/test.testbin: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by /usr/local/lib/libopen-pal.so.6)
*** Aborted at 1498292345 (unix time) try "date -d @1498292345" if you are using GNU date ***
PC: @     0x7f72e7e165fe MPI_Comm_rank
*** SIGSEGV (@0x44000098) received by PID 22747 (TID 0x7f72f92607c0) from PID 1140850840; stack trace: ***
    @     0x7f72f8742390 (unknown)
    @     0x7f72e7e165fe MPI_Comm_rank
    @     0x7f72f8b01ca7 caffe::GlobalInit()
    @           0x7583ad main
    @     0x7f72efe23830 __libc_start_main
    @           0x75d2c9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)
src/caffe/test/CMakeFiles/runtest.dir/build.make:57: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 139
CMakeFiles/Makefile2:296: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:303: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:227: recipe for target 'runtest' failed
make: *** [runtest] Error 2
```

Seem like still link to wrong opencl , do you success to run test ?
