### ISSUE TITLE
gpu numbers on mpi

### ISSUE THREAD

**Issue by zhihaolee** [yjxiong/caffe#149]
Hi,

how many GPUs at most can we use when using mpi running? I found that when I use 4 GPUs, it's ok, but when I use more than 4 GPUs, errors occur which look like "check failed: error == cudaSuccess ( 77 vs. 0 )".

Thanks in advance.

**Comment by yjxiong** [comment]
CUDA error 77 means "illegal memory access". Can you provide your model configs to reproduce the problem?

We have run with 4, 8, 16 GPU nodes and 4 nodes of 8 GPUs with Infiniband interconnect. There is not limit on the number of GPUs.

**Comment by yjxiong** [comment]
@zhihaolee  any luck?
