### ISSUE TITLE
difference between train_val_fast and train_val

### ISSUE THREAD

**Issue by zhihaolee** [yjxiong/caffe#15]
@wanglimin Hey, thank you for your work. When I test your models with the vgg_16_rgb_train_val_fast.prototxt, the accuracies are lower than that of your statement. I wonder if there  are differences between train_val_fast and train_val which lead to the different accuracies.
Thank you in advance!

**Comment by yjxiong** [comment]
@wanglimin 

"_fast" does not mean capacity reduction. It actually means we used the "Gather" trick to avoid bulky communication during training. So this would not lead to performance compromise.

On the performance side, here are a few tips we got from previous users' feedback:
- Please use the optical flow extraction tools we recommend if you are testing the released trained models. Or you can download the extracted optical flow images directly.
- To get the results reported, please use the matlab scripts provided to process the raw CNN output.

**Comment by antran89** [comment]
Hi @yjxiong , @wanglimin 
I also have the same issues with reproducing the results. Because I cannot download the flow data from your server, so I extracted the flow images of UCF101 by myself. I obtaned 79.2% accuracy for spatial-CNN and  83.3% for temporal-CNN with _your provided models_. However, when I retrained the model from your provided scripts, the results dramatically decrease. I obtained 76.1% for temporal-CNN. Why is the discrepancy? Is there any special tricks for the prototxt files? I used your original prototxt file.
I also observed that the flow image that I extracted has some weird. It is very common that in 2 consecutive flow frames, there would be an flow frame that does not have shape. See the following images for 2 consecutive frames (v_ApplyEyeMakeup_g01_c01, frame 1 and frame 2). Could you please check your data, and let me know? Many thanks,

![flow_x_0001](https://cloud.githubusercontent.com/assets/2399449/11861092/911019d4-a4b7-11e5-806f-cf51a13b80c7.jpg)
![flow_x_0002](https://cloud.githubusercontent.com/assets/2399449/11861097/9c7b3da8-a4b7-11e5-8cdc-d34e18be2791.jpg)

**Comment by yjxiong** [comment]
@antran89 

Hi, thanks for spotting the flow problem! Would you please try use the old flow tool 

https://github.com/wanglimin/dense_flow

to extract the flow images?

The one from my github repo is refactored recently, there might be some data race which leads to these empty frames. I will be looking into it asap. For now, you can use the old flow tool to see if you can reproduce the performance.

**Comment by yjxiong** [comment]
@antran89 

Hi, the optical flow tool in my repo is fixed. Now both tools will produce the same results.

**Comment by antran89** [comment]
Hi @yjxiong 
The above images are produced from the link you provided in your project page which points to Wang Limin's dense_flow. I think the data race in the old flow tool is still there.
I will look at your repo and I'll let you know.

**Comment by antran89** [comment]
Hi @yjxiong 
I tested dense_flow of your repo https://github.com/yjxiong/dense_flow.git. The behaviours is the same. Could you please try to execute the code running on video`v_ApplyEyeMakeup_g01_c01.avi` of UCF101. I do not know whether it is the problem of the code or the codec in my workstation. Please try again and let me know. Thank a lot.

**Comment by yjxiong** [comment]
If you get the error by using Limin's flow tool (the old one). It might be the problem of codec or something. We have been using the tool extensively and it worked properly. There is no data race in the old tool.

I will look at the video you mentioned and see if I can reproduce the problem.

**Comment by wanglimin** [comment]
Hi An Tran,

It is very common that there is no flow shape between consecutive frames of
ucf101 video clips. I also encounter this problem during my experiments.

For temporal CNN training, did you strictly follow our paper, such like
batch size, the number of iterations, mulit-scale cropping etc.?

Best regards,

Limin

On Thu, Dec 17, 2015 at 5:17 AM, An Tran notifications@github.com wrote:

> Hi @yjxiong https://github.com/yjxiong , @wanglimin
> https://github.com/wanglimin
> I also have the same issues with reproducing the results. Because I cannot
> download the flow data from your server, so I extracted the flow images of
> UCF101 by myself. I obtaned 79.2% accuracy for spatial-CNN and 83.3% for
> temporal-CNN with _your provided models_. However, when I retrained the
> model from your provided scripts, the results dramatically decrease. I
> obtained 76.1% for temporal-CNN. Why is the discrepancy? Is there any
> special tricks for the prototxt files? I used your original prototxt file.
> I also observed that the flow image that I extracted has some weird. It is
> very common that in 2 consecutive flow frames, there would be an flow frame
> that does not have shape. See the following images for 2 consecutive frames
> (v_ApplyEyeMakeup_g01_c01). Could you please check your data, and let me
> know? Many thanks,
> 
> [image: flow_x_0001]
> https://cloud.githubusercontent.com/assets/2399449/11861092/911019d4-a4b7-11e5-806f-cf51a13b80c7.jpg
> [image: flow_x_0002]
> https://cloud.githubusercontent.com/assets/2399449/11861097/9c7b3da8-a4b7-11e5-8cdc-d34e18be2791.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/15#issuecomment-165333098.

## 

Limin Wang
Post-doctoral Researcher, CVL, ETH, Zurich
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by antran89** [comment]
Hi @wanglimin,
Thanks for the insights. I have used your original prototxt file in [https://github.com/yjxiong/caffe/tree/action_recog/models/action_recognition]. I will check if your file is properly written.
Best regards,

**Comment by yjxiong** [comment]
One more thing to check.
In #14 you mentioned you are training with 1 GPU. How many GPUs are you using now? 
Please note that the actual batch size is `num_device * iter_size * batch_size`. If you are using 1 GPU, the other two parameters must be increased to meet the actual batch size under 4 devices situations.

**Comment by antran89** [comment]
Hi @yjxiong,
Thank for the hints. I increase 2 times for `iter_size` and `batch_size`. Currently, I am running experiments, when I had the results, I'll let you know.

**Comment by zhihaolee** [comment]
@yjxiong Thank you, I just got the validation results of using the matlab scripts to validate the spatial model, and the accuracy turned out to be 80.148%. So the reason is really about the matlab scripts! Is it a little shock for you guys to see the higher accuracy using everything provided by you, your script and model?I don't know the increasing reason, what do you think?

**Comment by yjxiong** [comment]
It's OK to see minor difference in performance numbers. Anyway, good to know you can reproduce the results.

**Comment by antran89** [comment]
Hi @yjxiong.
I can reproduce the performance of spatial-CNN which achieves very good performance with the Python classification script that I wrote (achieve `81.4%` on split 1).
However, I cannot reproduce good results on motion-CNN. The maximum performance that I can obtain is `82.92%`, a far distance from your report result `85.7%`. 
I also discovered that scale ratios in [link](https://github.com/yjxiong/caffe/blob/action_recog/models/action_recognition/vgg_16_flow_train_val_fast.prototxt#L20) is 

```
scale_ratios: [1,.875,.75]
```

It lacks one scale behind the technical report. Do you think it is the cause for degrading performance? Have you used this parameters in doing experiments for technical reports?
Thanks,
