### ISSUE TITLE
Do you just sample a RGB frame to represent one video in a iteration?

### ISSUE THREAD

**Issue by newzhx** [yjxiong/caffe#151]
I have a question: you said that you sampled one snippet  from the whole video during each iteration, while a snippet composed of a RGB frame or 10 continuous flow frames. I'm not sure whether my understanding is correct that you just use a frame or 10 continuous flow frames to represent a whole video in a iteration?

**Comment by yjxiong** [comment]
The sampled frame is not representing the video. It is just inheriting the video's label. 

Basically, two-stream CNNs are only training frame-level models. If you need video-level modeling, please check out the recent [TSN framework](https://github.com/yjxiong/temporal-segment-networks).
