### ISSUE TITLE
Could NOT find HDF5

### ISSUE THREAD

**Issue by ElaineHjx** [yjxiong/caffe#152]
When I tried to compile, it reports "Could NOT fine HDF5". But I've actually install HDF5 already. Could you please tell me how can I fix this problem?

hjx@rubick-ubuntu:~/Task1_ResNet/craftGBD/caffe_fast_rcnn_fast/build$ cmake ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/local/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
CMake Error at /usr/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find HDF5 (missing: HDF5_HL_LIBRARIES) (found version "1.8.11")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.6/Modules/FindHDF5.cmake:707 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:27 (find_package)
  CMakeLists.txt:30 (include)

-- Configuring incomplete, errors occurred!
See also "/home/hjx/Task1_ResNet/craftGBD/caffe_fast_rcnn_fast/CMakeFiles/CMakeOutput.log".
See also "/home/hjx/Task1_ResNet/craftGBD/caffe_fast_rcnn_fast/CMakeFiles/CMakeError.log".

**Comment by wlgcqh** [comment]
Have you solved this problem?I encountered the same problem.

**Comment by yjxiong** [comment]
Please check your environmental variables. In most cases, there are some conflicting configurations that scramble the CMake's package finding process.

**Comment by yjxiong** [comment]
Hi @ElaineHjx ,

Have you figured out the problem?

**Comment by ElaineHjx** [comment]
Hi @yjxiong ,
Thank you for your reply, but the problem has not solved yet. I wonder if I can make this fast-rcnn by using a "Makefile.config" rather than "cmake..". You know, build like the regular caffe model. Is that OK? Thank you very much!

**Comment by yjxiong** [comment]
I would not suggest doing so. As it is not tested.

Would you please check whether you put Anaconda's bin path in your PATH variable?

**Comment by yjxiong** [comment]
@ElaineHjx Any luck?
