### ISSUE TITLE
HMDB51 model and configurations.

### ISSUE THREAD

**Issue by carloscaetano** [yjxiong/caffe#154]
Hi,

Could you, please, release the HMDB51 model and configurations that you used? (deploy.prototxt, solver.prototxt and vgg_16_flow_train_val_fast.prototxt).

Thanks in advance. :-)

**Comment by yjxiong** [comment]
Hi @carloscaetano ,

We did not experiment with HMDB51 in the report. If you need help with that, please refer to our latest work [temporal segment networks](https://github.com/yjxiong/temporal-segment-networks).

**Comment by carloscaetano** [comment]
Thanks for the response @yjxiong . However, I really need to run HMD51 using this caffe model....

I tried to run it with HMDB51, so the only modification that I did was to change the number of outputs on the fc8 layer from 101 to 51. However the outputs are zeros and "nan" on all layers on the 40 Iteration such as:

[Backward] Layer conv1_2, param blob 0 diff: nan
[Backward] Layer conv1_2, param blob 1 diff: 0

it also happen on [Forward]

Do you think it is because we have very little data on HMDB51? Could you, please, give me any advice on how to train this model with HMDB51?

Thanks in advance.

**Comment by yjxiong** [comment]
Please consult these solver configs if you insist:

https://github.com/yjxiong/temporal-segment-networks/blob/master/models/hmdb51/tsn_bn_inception_flow_solver.prototxt

https://github.com/yjxiong/temporal-segment-networks/blob/master/models/hmdb51/tsn_bn_inception_rgb_solver.

There should be no problem running on HMDB51. It is only relatively smaller than UCF101 but still of a reasonable volume.

**Comment by yjxiong** [comment]
@carloscaetano do you still meet this problem?

**Comment by carloscaetano** [comment]
@yjxiong The solver configs you told helped me. Thank you so much. :-)
Sorry for not answering earlier.

**Comment by yjxiong** [comment]
Great to know!
Closing this. Please feel free to reopen it if you meet any further problem.
