### ISSUE TITLE
“frozen”在bn_layer中是什么意思？

### ISSUE THREAD

**Issue by ghost** [yjxiong/caffe#159]
你好，我想请教一下`frozen`这个参数在bn_layer中扮演的是什么角色呢？
另：我在验证ResNet的时候没有发现`use_global_stats`，并且网络不收敛，我想是否需要把`frozen`设为true?
Thanks!

**Comment by yjxiong** [comment]
frozen表示将BN layer视作普通的逐通道线性变换来进行运算。
一般情况下frozen使用默认值(false)即可。
