### ISSUE TITLE
how to use pycaffe

### ISSUE THREAD

**Issue by ArsenLuca** [yjxiong/caffe#160]
After make && make install, when I locate the PYTHONPATH to ./caffe/python/caffe, when running in python, python gives the error "Import Error: NO module named caffe"
So, where is the true PYTHONPATH?

**Comment by yjxiong** [comment]
I guess you should use ./caffe/python cuz you are importing the whole package here.

**Comment by ArsenLuca** [comment]
I find the problem:

![1_](https://cloud.githubusercontent.com/assets/23271554/25699681/cc770c4a-30f6-11e7-9da4-0d18eabb233f.jpg)

The PythonInterp searched by cmake is in anaconda, but the PythonLibs is the default python.
How can I change the PythonLibs searched by cmake to anaconda?

**Comment by yjxiong** [comment]
This is OK cuz the two are the same. 

As I said, you should change your PYTHONPATH setting.

**Comment by ArsenLuca** [comment]
I see. 
But the python interface is not built successfully.  I thought it's caused by the conflict between two python version. 
A few minutes before, I found the information outputted by Cmake shows that "Could not find Boost".
But I installed boost in anaconda.
So why find_package function failed to find Boost?

**Comment by yjxiong** [comment]
It needs the boost version >= 1.55, installed by apt-get or from sources. I didn't know one can install that "in Anaconda".

**Comment by ArsenLuca** [comment]
OK, I tried boost version 1.53, that's fine~

**Comment by yjxiong** [comment]
Please try 1.55 or higher then.

**Comment by ArsenLuca** [comment]
ok, I will try




发自网易邮箱大师


On 05/5/2017 12:02，yjxiong<notifications@github.com> wrote：

Please try 1.55 or higher then.

**Comment by yjxiong** [comment]
@ArsenLuca 
Any luck?

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.

**Comment by ArsenLuca** [comment]
Sorry, I missed the emails before. 
I still have not chance to try version 1.55+, cuz I have no sudo authority on our server. :(
All in all, thank you for your help
