### ISSUE TITLE
Can not load new models?

### ISSUE THREAD

**Issue by payymann** [yjxiong/caffe#162]
I have build the code, But when I want to load a model such as https://github.com/pertusa/InceptionBN-21K-for-Caffe , It can not load the model. It seems that this version of caffe can not load newer models that written with new net parameter formats. The error that occurs is this : 

> [libprotobuf ERROR google/protobuf/text_format.cc:299] Error parsing text-format caffe.NetParameter: 6:15: Message type "caffe.LayerParameter" has no field named "input_param".
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> F0512 15:11:06.415004  4536 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /$(HOME)/(USER)/caffe_test/deploy.prototxt
> *** Check failure stack trace: ***
> Aborted (core dumped)

**Comment by yjxiong** [comment]
Changing the first few lines of your proto from 

```
layer { 
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 10 dim: 3 dim: 224 dim: 224 } }
}
```

to 
```
input: "data"
input_dim: 10
input_dim: 3
input_dim: 224
input_dim: 224
```

or 

```
input: "data"
input_shape {
  dim: 10
  dim: 3
  dim: 224
  dim: 224
}
```

should solve your problem.

There isn't much changed except the adding of this `Input` layer, which I don't see a must. But if you really need it in your proto, you can add it to the codebase to make the original prototxt load.

**Comment by yjxiong** [comment]
@peyyman Any luck?
