### ISSUE TITLE
Question in VideoSpatialPrediction.py

### ISSUE THREAD

**Issue by bryanyzhu** [yjxiong/caffe#167]
Hi guys,

Thanks for the great framework. I just have a quick question in the file VideoSpatialPrediction.py. What does np.transpose in these two lines mean?  Especially the first one, why do we need to change the order of width and height? Thanks a lot.

```
Line 63: rgb = np.transpose(rgb, (1,0,2,3))

Line 72: net.blobs['data'].data[...] = np.transpose(rgb[:,:,:,span], (3,2,1,0))
```

**Comment by yjxiong** [comment]
This file is contributed by users. I didn't verify its correctness. 

For a complete example of Python inference, I refer you to the TSN code base.
 https://github.com/yjxiong/temporal-segment-networks

**Comment by bryanyzhu** [comment]
Thanks @yjxiong , I will look at TSN code base. Closing this.
