### ISSUE TITLE
different file sizes between original caffemodel files and the re-saved ones

### ISSUE THREAD

**Issue by zhihaolee** [yjxiong/caffe#17]
Hi, @yjxiong  @wanglimin  thank you for your kindness!
I want to reproduce the pre-trained model for temporal stream. when I used the matlab interface to load the caffe model parameters from the provided caffemodel files, and just simply save the models using the net.save() function, the new sizes of the re-saved caffemodel files are different from the original ones.
For your vgg_16_action_flow_pretrain.caffemodel, the file size of the one you provided is 537083852, the file size of the reproduced one by me is 538738782, as for caffenet, the original file size is 243862418, the re-saved one is 243862097, as for vggnet, the original file size is 553432081, the re-saved one is 553432454. Though the differences are very slight, I still want to know why.
Hope you bother to tell me, thank you in advance!

**Comment by yjxiong** [comment]
I am not a guru in Protobuffer. My guess is that there is extra information stored during each serialization, so the file size may change from time to time.
As long as the stored data is not changed, I don't consider this a problem.

**Comment by yjxiong** [comment]
I am closing the issue for now. Please feel free to reopen it if you find data loss due to this behaviour.
