### ISSUE TITLE
Have any experiments on HMDB51 dataset?

### ISSUE THREAD

**Issue by fanser** [yjxiong/caffe#170]
Hello, do you have the trained model on HMDB51 dataset? 
recently, I want to do some experiment on HMDB51 and need the pretrained 2-stream model. But i didn't find something about it.

**Comment by yjxiong** [comment]
If you just need some trained models. You can refer to the TSN repo where we have released models trained on HMDB51.

https://github.com/yjxiong/temporal-segment-networks
