### ISSUE TITLE
Error with Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by linquanxu** [yjxiong/caffe#174]
hi, There was an error happened on MobileNet(be similar with resnet50).
![qq 20170622110536](https://user-images.githubusercontent.com/16631303/27415746-43757006-573b-11e7-939f-ffd1f19532d4.png)
![b](https://user-images.githubusercontent.com/16631303/27415980-133c1cbc-573d-11e7-9791-36bab6b9ba8c.png)

I guess it might be that the parameter group is too big. How to fix it? thanks.

**Comment by yjxiong** [comment]
I guess it's due to the large group number applied to cuDNN. Try using `engine: CAFFE` as a workaround in these layers.

**Comment by linquanxu** [comment]
ok，thanks for your response.
