### ISSUE TITLE
Can we make optimize_test to be true by default?

### ISSUE THREAD

**Issue by wk910930** [yjxiong/caffe#176]
Dear @yjxiong ,

I noticed that `optimize_test` ([here](https://github.com/yjxiong/caffe/blob/mem/src/caffe/proto/caffe.proto#L1329-L1330)) is set to `false` by default. I was wondering if there is any concerns if we set it `true`. I cannot think of one situation where we don't want to save memory.

Thanks!
Kun

**Comment by yjxiong** [comment]
Hi @wk910930 ,

This default setting is to make it compatible with existing codes written with Python/Matlab interfaces, which sometimes retrieve intermediate blobs for uses.  Optimizing test memory by default will corrupt these blobs without notice, thus breaking the codes. 

But I agree with you that for the case of command line training and validation it is better to set `optimize_test` to true. We may consider making a special rule for Python/Matlab interface instead.

**Comment by wk910930** [comment]
Thanks! Closing the issue.
