### ISSUE TITLE
Why should we reset diff to zero if layer is not backpropagated ? 

### ISSUE THREAD

**Issue by hiyijian** [yjxiong/caffe#179]
hi, @yjxiong ,
  I noticed you commented "Manually set the bottom diff to zero if it is not backpropagated. If not set, they may be corrupted when memory optimization is on" in net::BackwardFromTo(.. ) of net.cpp. Why is that?  
  By the way, It seems that all host buffers are allocated by malloc instead of cudaMallocHost. Why is that?

  Thanks

**Comment by yjxiong** [comment]
cudaMalloc host allocates page-lock memories to provide high-speed transmission between GPUs and CPUs. CUDA doc says
```
Allocating excessive amounts of memory with cudaMallocHost() may degrade system performance, since it reduces the amount of memory available to the system for paging.
```
It is also not necessary as Caffe does not require very-high data transmission bandwidth.
