### ISSUE TITLE
Cannot download the VGG initialization models

### ISSUE THREAD

**Issue by mengxi-jp** [yjxiong/caffe#180]
Hi, yjxiong,

I also would like to try your trained VGG-16 models.
But the model download links under caffe/models/action_recognition/ are unavailable now.
Could you help to look at the issue?
Thanks in advance.

**Comment by zbwglory** [comment]
The download links are now available.

**Comment by mengxi-jp** [comment]
Thank you for your reply.
But I still found the links of the initialization models were not available.

"The requested URL /pretrain/vgg_16_action_rgb_pretrain.caffemodel was not found on this server."
"The requested URL /pretrain/vgg_16_action_flow_pretrain.caffemodel was not found on this server."

**Comment by yjxiong** [comment]
The links are fixed now. Please try again.
Sorry for any inconvenience caused.

**Comment by mengxi-jp** [comment]
Thank you for your help.
I can download now.

**Comment by cyh-github** [comment]
I face with the same problem now.The link is unavilable.
