### ISSUE TITLE
What version of OpenMPI and GCC are used with CUDA 8.0 and CuDNN 6.1?

### ISSUE THREAD

**Issue by jesimonbarreto** [yjxiong/caffe#182]
Hi yjxiong,
Using an environment with the following software specifications:
-CUDA 8.0
-CuDNN 6.1
-OpenCV 3.2.0
What versions of OpenMPI and GCC should we use?

Thank you in advance.

**Comment by yjxiong** [comment]
OpenMPI > 1.8.7 should be ok. No specific GCC version is required.

**Comment by jesimonbarreto** [comment]
thank you so much.
