### ISSUE TITLE
model files 

### ISSUE THREAD

**Issue by fizamurtaza** [yjxiong/caffe#187]
hello
I am unable to download any of the model files 
http://mmlab.siat.ac.cn/very_deep_two_stream_model/cuhk_action_temporal_vgg_16_split1.caffemodel
 i am getting following error

![image](https://user-images.githubusercontent.com/25634081/32317334-4eb2c650-bfd5-11e7-8e9d-82d113bdebed.png)

please help me in downloading them.

**Comment by yjxiong** [comment]
Models were all migrated out of the SIAT server last month. There should be no problem in downloading right now.
