### ISSUE TITLE
Does this caffe support multiGPU training with Python Layer such as py-Faster Rcnn?

### ISSUE THREAD

**Issue by go2star** [yjxiong/caffe#193]
Does this caffe support multiGPU training with Python Layer such as py-Faster Rcnn?

**Comment by zzy123abc** [comment]
Python layer does not support multiGPU training,please use c++ command api.

**Comment by yjxiong** [comment]
@go2star 

Basically, yes. Python layer is ok with MPI based parallel. You may need to modify some layers in your use cases.
