### ISSUE TITLE
MPI exception

### ISSUE THREAD

**Issue by jetyingjia** [yjxiong/caffe#200]
@yjxiong 
when I use this project, I meet this problem. Is thers something wrong with my progrom.
It come offen when training thousands iterations.
Thank you in advance!

*** Aborted at 1520509287 (unix time) try "date -d @1520509287" if you are using GNU date ***
PC: @     0x7fc0d60a9414 __pthread_cond_wait
*** SIGTERM (@0x7d100008c74) received by PID 35967 (TID 0x7fc0d7fa7a40) from PID 35956; stack trace: ***
    @     0x7fc0d670bd40 (unknown)
    @     0x7fc0d60a9414 __pthread_cond_wait
    @     0x7fc0d795a3f3 boost::condition_variable::wait()
    @     0x7fc0d795849b caffe::MPIComm::WaitAll()
    @     0x7fc0d79438e2 caffe::Solver<>::SyncGradient()
    @     0x7fc0d794d55b caffe::Solver<>::Step()
    @     0x7fc0d794d7f8 caffe::Solver<>::Solve()
    @           0x408ba2 train()
    @           0x406fc6 main
    @     0x7fc0d66f6ec5 (unknown)
    @           0x40757d (unknown)
    @                0x0 (unknown)
--------------------------------------------------------------------------
mpirun noticed that process rank 4 with PID 0 on node node7427 exited on signal 9 (Killed).

**Comment by yjxiong** [comment]
`PID 0 on node node7427 exited on signal 9 (Killed).`

Is this program killed due to OOM? Maybe run a `sudo dmesg` to see what happened when you meet the problem again.

**Comment by jetyingjia** [comment]
@yjxiong I find when training, the memory is not a fixed value and is becoming larger, and then this happend.  Is a memory leaks problem?

**Comment by jetyingjia** [comment]
@yjxiong dmesg is below:

Out of memory: Kill process 33049 (caffe) score 123 or sacrifice child
Killed process 33049 (caffe) total-vm:118020040kB, anon-rss:32252368kB, file-rss:83732kB

**Comment by yjxiong** [comment]
Yes it is an OOM kill. Normally our models use constant memory. Are you adding any custom layer or having some special architecture?

**Comment by jetyingjia** [comment]
@yjxiong It occures when traing ARTNet-18, but C3D-resnet18 is OK. ALL models and prototxt is official released. 
wanglimin/ARTNet: Appearance-and-Relation Networks
https://github.com/wanglimin/ARTNet

**Comment by yjxiong** [comment]
It could happen if some newly added layer is using too much CPU memory. Please consult the authors for the problem.
