### ISSUE TITLE
MPI error when training with multiple GPUs

### ISSUE THREAD

**Issue by carloscaetano** [yjxiong/caffe#201]
Hi,

I'm getting this error when training with multiple GPUs with MPI. I am using CUDA 8.0, cuDNN 5.1, OpenBLAS.

*** Aborted at 1521239634 (unix time) try "date -d @1521239634" if you are using GNU date ***
PC: @     0x7f9088a9fd15 __memcpy_ssse3_back
*** SIGSEGV (@0x7f8fe1900000) received by PID 96777 (TID 0x7f8fd93fd700) from PID 18446744073198895104; stack trace: ***
PC: @     0x7fe5de0aad15 __memcpy_ssse3_back
*** SIGSEGV (@0x7fe531700000) received by PID 96776 (TID 0x7fe54e3fe700) from PID 829423616; stack trace: ***
    @     0x7f909c30a5e0 (unknown)
    @     0x7fe5f19155e0 (unknown)
    @     0x7f9088a9fd15 __memcpy_ssse3_back
    @     0x7fe5de0aad15 __memcpy_ssse3_back
    @     0x7f9063d5e477 (unknown)
    @     0x7fe5b9369477 (unknown)
    @     0x7f90634bae67 (unknown)
    @     0x7fe5b8ac5e67 (unknown)
    @     0x7f90634b211d (unknown)
    @     0x7fe5b8abd11d (unknown)
    @     0x7f9061feced0 (unknown)
    @     0x7fe5b75f7ed0 (unknown)
    @     0x7f9061ff5123 (unknown)
    @     0x7fe5b7600123 (unknown)
    @     0x7f908958c1a0 (unknown)
    @     0x7fe5deb971a0 (unknown)
    @     0x7f909cb90d8e caffe::MPIComm::DispatchJob()
    @     0x7fe5f219bd8e caffe::MPIComm::DispatchJob()
    @     0x7f909cb9103c caffe::MPIComm::ThreadFunc()
    @     0x7fe5f219c03c caffe::MPIComm::ThreadFunc()
    @     0x7f909c52427a (unknown)
    @     0x7fe5f1b2f27a (unknown)
    @     0x7f909c302e25 start_thread
    @     0x7fe5f190de25 start_thread
    @     0x7f9088a4d34d __clone
    @     0x7fe5de05834d __clone

Any idea of what it could be? :-/

**Comment by victorhcm** [comment]
What is your MPI version? Does it work with a single GPU?

**Comment by carloscaetano** [comment]
MPI version is 2.0.0. It works fine with a single GPU. The problem is just with multiple GPUs.

**Comment by carloscaetano** [comment]
I changed it to MPI 1.8.7 and now it is working fine. So I will close the issue.
