### ISSUE TITLE
MPI error

### ISSUE THREAD

**Issue by ZhangLin-PKU** [yjxiong/caffe#209]
Hi, @yjxiong thanks a lot for your code.

I get an error when I run command under your instruction on 'Training with multiple GPUs'. Here is the command:

`mpirun -n 2 /home/imre/zlin/code/caffe train -solver step_1_resnet101_solver.prototxt -weights ../../models/resnet101.caffemodel`

Here is the error info:

```
Open MPI tried to fork a new process via the "execve" system call but
failed.  Open MPI checks many things before attempting to launch a
child process, but nothing is perfect. This error may be indicative
of another problem on the target host, or even something as silly as
having specified a directory for your application. Your job will now
abort.

  Local host:        imre
  Application name:  /home/imre/zlin/code/caffe
  Error:             Permission denied
--------------------------------------------------------------------------
[imre:21345] 3 more processes have sent help message help-orte-odls-default.txt / execve error
[imre:21345] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

How can I fix it and successfully train network?

**Comment by yjxiong** [comment]
`mpirun -n 2 /home/imre/zlin/code/caffe`

Are you sure this executable is the one you built?

```
  Local host:        imre
  Application name:  /home/imre/zlin/code/caffe
  Error:             Permission denied
```

Do you have the `x` permission on this file?

**Comment by ZhangLin-PKU** [comment]
Sorry, I assigned the path to caffe directory to it...

I tried /path/to/caffe/build/install/bin/caffe and everything goes right.

Thank you for your help!
