### ISSUE TITLE
Compilation fails when not using cudnn

### ISSUE THREAD

**Issue by agethen** [yjxiong/caffe#21]
Hey, I found a minor issue: Using g++ 5.2.1, with a cuda-only (no cudnn) installation and USE_CUDNN disabled, compilation failes when evaluating CUDNN_VERSION_MIN in common_layers.hpp and layer_factory.cpp. Breaking the if condition into two solves the issue :)

**Comment by yjxiong** [comment]
Thanks for pointing out the problem!

I have also found this breakage when enabling travis CI. So it has been fixed in #20 
Compilation should now work properly in no cuDNN situations.

**Comment by yjxiong** [comment]
@agethen 
Please have a try of the latest commit. It should fix your problem.

Thanks again for letting us know the problem!

**Comment by agethen** [comment]
@yjxiong Thank you, I can confirm it compiles fine now :)
