### ISSUE TITLE
请问在centos7上编译为什么出现../lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'

### ISSUE THREAD

**Issue by ahwangyuwei** [yjxiong/caffe#215]
怎么解决呢？
谢谢

**Comment by chenliqiong** [comment]
应该是opencv_imgcodecs链接的问题，把opencv需要的lib添加到Makefile文件中    
找到LIBRARIES（在PYTHON_LIBRARIES := boost_python python2.7 前一行）并修改为：（在最后增加opencv_imgcodecs）
LIBRARIES += glog gflags protobuf leveldb snappy \
        lmdb boost_system hdf5_hl hdf5 m \
        opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs
