### ISSUE TITLE
Would it possible for you to provide the feature extraction demo of 3D branch?

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [yjxiong/caffe#216]
Hello, Xiong.
Would it possible for you to provide a feature extraction demo of the 3D branch? Or is it any similar code for reference?  Thx~

**Comment by jx-zhong-for-academic-purpose** [comment]
Another question：For the 3D  branch, is there any pre-trained model released?

**Comment by wanglimin** [comment]
The 3D branch is for the ARTNet paper and please see its repo:

https://github.com/wanglimin/ARTNet

**Comment by jx-zhong-for-academic-purpose** [comment]
万分感谢~
