### ISSUE TITLE
cancelled

### ISSUE THREAD

**Issue by Helenll** [yjxiong/caffe#217]
cancelled

**Comment by Helenll** [comment]
After starting a container, I use 'env' and find a variable seems to indicate that cudnn‘s version is 7, so I suppose that it is already included in the tsn image.
I use 'build_all' to install the caffe, then dose this caffe support cuda9 and cudnn7?Or in other words, is this caffe the same as that in the tsn image? After 2016, is any difference made in the caffe and put in tsn docker image?

Thanks.

**Comment by yjxiong** [comment]
The docker file for the tsn image is here

https://github.com/yjxiong/temporal-segment-networks/blob/docker/Dockerfile

Its CUDA9, cuDNNv7

**Comment by Helenll** [comment]
Thanks for your reply!
May I confirm that  this repository(https://github.com/yjxiong/caffe) also support CUDA9, cuDNNv7?
The docker image is very helpful, but I still need to build caffe in an environment. In ubuntu16.04 I have installed cuda9.0, cudnn7 ,openmpi, and downloaded temporal-segment-networks in advance. So I:
$MPI_PREFIX=/usr/local/openmpi bash build_all.sh MPI_ON
  -- CUDA is not detected by cmake
******************* Caffe Configuration Summary *******************
    -- Dependencies:
    --   OpenCV            :   Yes (ver. 2.4.13)
    --   CUDA              :   No
…...
All tools built. Happy experimenting!

I cp the example to Makefile.config, enable USE_CUDNN := 1 and reinstall, but
tools/CMakeFiles/caffe.bin.dir/build.make:133: recipe for target 'tools/caffe' failed
make[2]: *** [tools/caffe] Error 1
CMakeFiles/Makefile2:401: recipe for target 'tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
.......
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build Caffe. Please check the logs above.

May I exclude the case of not supporting  CUDA9, cuDNNv7?
Thank you very much for your help!

**Comment by yjxiong** [comment]
`CUDA is not detected by cmake` it is not detected, not unsupported. You should check your environment.

**Comment by ShawKai666** [comment]
> Thanks for your reply!
> May I confirm that this repository(https://github.com/yjxiong/caffe) also support CUDA9, cuDNNv7?
> The docker image is very helpful, but I still need to build caffe in an environment. In ubuntu16.04 I have installed cuda9.0, cudnn7 ,openmpi, and downloaded temporal-segment-networks in advance. So I:
> $MPI_PREFIX=/usr/local/openmpi bash build_all.sh MPI_ON
> -- CUDA is not detected by cmake
> ******************* Caffe Configuration Summary *******************
> -- Dependencies:
> -- OpenCV : Yes (ver. 2.4.13)
> -- CUDA : No
> …...
> All tools built. Happy experimenting!
> 
> I cp the example to Makefile.config, enable USE_CUDNN := 1 and reinstall, but
> tools/CMakeFiles/caffe.bin.dir/build.make:133: recipe for target 'tools/caffe' failed
> make[2]: *** [tools/caffe] Error 1
> CMakeFiles/Makefile2:401: recipe for target 'tools/CMakeFiles/caffe.bin.dir/all' failed
> make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
> .......
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> Failed to build Caffe. Please check the logs above.
> 
> May I exclude the case of not supporting CUDA9, cuDNNv7?
> Thank you very much for your help!

I have encountered the same problem with you, but my cuda can be detect and ask how you solved it.
