### ISSUE TITLE
BN Freeze with cuDNN

### ISSUE THREAD

**Issue by yjxiong** [yjxiong/caffe#23]
The freeze option with cuDNN's batch normalization seems to be not working properly.

@Cysu please have a look if you got some spare time.

cc @wanglimin

**Comment by wanglimin** [comment]
When I freeze the bn layer, at Iteration 0, I got the log as follows:
I0104 05:03:12.070287 21304 net.cpp:730]     [Update] Layer conv1/7x7_s2, param 0 data: 0.0557161; diff: 1.41879e-06
I0104 05:03:12.070413 21304 net.cpp:730]     [Update] Layer conv1/7x7_s2, param 1 data: 0.2; diff: 8.5712e-08
I0104 05:03:12.070482 21304 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 0 data: 2.11268; diff: 0
I0104 05:03:12.070544 21304 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 1 data: 2.30605; diff: 0
I0104 05:03:12.070607 21304 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 2 data: 0; diff: 0
I0104 05:03:12.070670 21304 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 3 data: 0.999995; diff: 2.49999e-06

When not frozen, it is as follows:
I0104 05:07:03.566396 24673 net.cpp:730]     [Update] Layer conv1/7x7_s2, param 0 data: 0.0557161; diff: 6.96451e-07
I0104 05:07:03.566520 24673 net.cpp:730]     [Update] Layer conv1/7x7_s2, param 1 data: 0.2; diff: 9.19785e-19
I0104 05:07:03.566612 24673 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 0 data: 2.11268; diff: 1.3389e-12
I0104 05:07:03.566691 24673 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 1 data: 2.30605; diff: 8.37824e-13
I0104 05:07:03.566762 24673 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 2 data: 0.513124; diff: 1.28281e-06
I0104 05:07:03.566838 24673 net.cpp:730]     [Update] Layer conv1/7x7_s2_bn, param 3 data: 0.907656; diff: 2.26914e-06

**Comment by Cysu** [comment]
Yeah. It is a bug, and I have created the PR #24 to solve the problem by switching back to caffe engine when freeze BN.

**Comment by yjxiong** [comment]
Few issues:
- [x] A series of PR related to BN is on the way. We will remove the freezing function by absorbing the BN parameters into convolution filter/bias.
- [x] The flow model generation script has a small bug that discards the mean/var in source caffemodel. This has been fixed.

**Comment by yjxiong** [comment]
Frozen is working properly with #24 and #25 .

@Cysu is working on building a script to absorb the BN parameters into its previous layer's parameters.

**Comment by yjxiong** [comment]
Resolved with #26 , #25 , and #24
