### ISSUE TITLE
Complie with USE_MPI = off and run with 1 GPU

### ISSUE THREAD

**Issue by jerryl777** [yjxiong/caffe#27]
Hi, can the code run correctly with a single GPU ? 
Specailly, complies with USE_MPI = off ( already modify the batch_size related parameters ). Furthermore,  may I ask what server you used for training?  I found our Dell R720 can't support mutiple GPUs because of the power problem.

Thanks.

**Comment by yjxiong** [comment]
Sure it can. Travis CI verifies it.

It should run on single/multiple GPUs and also CPU-only.

If you encounter the power shortage, you can either use fewer GPUs or set a
lower application lock using nvidia-smi.

On Wednesday, January 6, 2016, cenjiepeng notifications@github.com wrote:

> Hi, can the code run correctly with a single GPU ?
> Specailly, complies with USE_MPI = off ( already modify the batch_size
> related parameters ) Furthermore, may I ask what server you used for
> training? I found our Dell R720 can't support mutiple GPUs because of the
> power problem
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/27.

## 

Best regards,

Yuanjun

**Comment by jerryl777** [comment]
@yjxiong , Thank you. Actually, we are going to purchase  the new server which will be configured with four GPUs. We are really worried about the power supply. Could you also give us the advice about the type of servers?

**Comment by yjxiong** [comment]
Usually power supply modules are provided by the server vendors, and they may provide a few options. On our servers we haven't met with power problems. My advice is to make sure the power limit with your vendors before purchases.

**Comment by jerryl777** [comment]
Thanks @yjxiong .
