### ISSUE TITLE
action_matlab运行问题

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#29]
老师，您好！
       非常感谢您分享。我在运行action-matlab例程时遇到一些问题，希望您能抽时间看一下是我哪里操作不对。谢谢！
       运行环境：Ubuntu14.04  matlabR2013b  caffe
       我编译好您分享的代码，用matlab文件夹内demo测试可以得到结果，但是在运行action-matlab时总是提示:Undefined variable “caffe” or class “caffe.reset_all".
       我尝试了添加路径的方法还是不行。麻烦老师看下是什么问题。再次感谢！

**Comment by wanglimin** [comment]
从这个错误看，应该是你的路径没有添加对，或者没有编译matcaffe。

**Comment by Jangol** [comment]
非常感谢老师！这个问题已经解决了。
但是我在编译您分享的opticla-flow-extraction时总是报错，不能给完全编译。
我是用的是OpenCV3.0,只有一块GPU。想问下老师您的编译环境是什么样的。

**Comment by wanglimin** [comment]
我们用的是2.8， 这个应该跟3.0不兼容。

**Comment by MenglaiWang** [comment]
@Jangol 同问你后面怎么解决的？多谢！
