### ISSUE TITLE
add script to create the optical-flow data

### ISSUE THREAD

**Issue by jianminsun** [yjxiong/caffe#30]
Since the dataset is very large, I am having a hard time to download it. Would you like to add the script for converting avi files to optical-flow frames?

**Comment by yjxiong** [comment]
We have the tools for flow extraction. Please go through the README for the
link to it.

On Wednesday, January 13, 2016, jianminsun notifications@github.com wrote:

> Since the dataset is very large, I am having a hard time to download it
> Would you like to add the script for converting avi files to optical-flow
> frames?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/30.

## 

Best regards,

Yuanjun

**Comment by jianminsun** [comment]
Thanks. I found the dense_flow.
Usage:
./denseFlow_gpu -f test.avi -x tmp/flow_x -y tmp/flow_x -i tmp/image -b 20 -t 1 -d 0 -s 1
Are these parameters exactly same as what you were using to create the dataset? I am trying to reproduce your paper's result.

**Comment by wanglimin** [comment]
@jianminsun ,

Yes, it is exactly the same as ours.

Limin

**Comment by jianminsun** [comment]
Thank you very much.
