### ISSUE TITLE
train_rgb_split1.txt

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#31]
@wanglimin 

ucf101_rgb_img/WallPushups/v_WallPushups_g21_c06 111 98
ucf101_rgb_img/StillRings/v_StillRings_g18_c02 192 85
ucf101_rgb_img/IceDancing/v_IceDancing_g19_c06 251 43
ucf101_rgb_img/Skijet/v_Skijet_g08_c04 208 81
ucf101_rgb_img/Lunges/v_Lunges_g13_c01 266 51
ucf101_rgb_img/CleanAndJerk/v_CleanAndJerk_g16_c04 105 20
ucf101_rgb_img/RopeClimbing/v_RopeClimbing_g13_c04 88 74
ucf101_rgb_img/BaseballPitch/v_BaseballPitch_g14_c01 103 6
ucf101_rgb_img/CuttingInKitchen/v_CuttingInKitchen_g16_c02 197 24
ucf101_rgb_img/SkateBoarding/v_SkateBoarding_g22_c04 85 79
ucf101_rgb_img/RockClimbingIndoor/v_RockClimbingIndoor_g18_c02 168 73
ucf101_rgb_img/FloorGymnastics/v_FloorGymnastics_g24_c01 174 29
ucf101_rgb_img/LongJump/v_LongJump_g16_c03 134 50
ucf101_rgb_img/BalanceBeam/v_BalanceBeam_g23_c04 106 4
ucf101_rgb_img/BoxingPunchingBag/v_BoxingPunchingBag_g12_c05 231 16
ucf101_rgb_img/Bowling/v_Bowling_g20_c02 133 15
ucf101_rgb_img/ThrowDiscus/v_ThrowDiscus_g13_c03 113 92
ucf101_rgb_img/Mixing/v_Mixing_g19_c03 101 53

标签中数字分别表示什么呢？

**Comment by wanglimin** [comment]
第一个数字表示视频的帧数，第二个表示视频的标签（从0开始）。

**Comment by yjxiong** [comment]
Closing as the question has been answered.

**Comment by double-vane** [comment]
how can I get the train_rgb_split1.txt by myself? Thank you

**Comment by yjxiong** [comment]
We have released a full fledge action recognition framework at

https://github.com/yjxiong/temporal-segment-networks

Please the section on training.

**Comment by double-vane** [comment]
@yjxiong Thank you

**Comment by double-vane** [comment]
@yjxiong 
I have a problem,size(flow_x_)=240_320, but in the  VideoTemporalPrediction.m,size(flow)=256_340..
I use the matlab2016,and the error is 带有下标的赋值维度不匹配,
if I replace the
 flow(1:m,1:n,(j-1)_2+1,i) = img_x(:,:); 
with
 [m,n]= size(img_x);
flow(1:m,1:n,(j-1)*2+1,i) = img_x(:,:);
Is right？
or I should use imresize(..[256,340])

**Comment by yjxiong** [comment]
@double-vane 
It depends on the size of your image. We always assume the images are of size 340 \* 256.
