### ISSUE TITLE
SpatialNet or TemporalNet?

### ISSUE THREAD

**Issue by jianminsun** [yjxiong/caffe#34]
In vgg_16_flow_train_val_fast.prototxt, the net name is : "CUHK_Action_SpatialNet".
In vgg_16_rgb_train_val_fast.prototxt, the net name is : "CUHK_Action_TemporalNet".

From your arxiv paper, I read this "The  spatial  net  is  built  on  a  single  frame  image (224×224×3) and therefore its architecture is the same as those for object recognition in image domain. The input of temporal net is 10-frame stacking of optical flow fields (224×224×20)."

Are they just simple typos? Or I misunderstood something here. Thanks.

**Comment by wanglimin** [comment]
There is a typo in the prototxt files. I have corrected this typo.

**Comment by jianminsun** [comment]
Thanks for the clarification.
