### ISSUE TITLE
How to use 'extractOpticalFlow.m' script

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#35]
@wanglimin 
when I run the 'extractOpticalFlow.m',it occured :

/bin/bash: ./extract_gpu: No such file or directory
......
cmd = sprintf('./extract_gpu -f %s -x %s -y %s -i %s -b 20',file1,file2,file3,file4);
        system(cmd);
    end

I  tried to addpath ,but it's no use.look forward to your help.Thanks.

**Comment by wanglimin** [comment]
First, you need to make sure that you compile extract_gpu sucessfully.

**Comment by Jangol** [comment]
@wanglimin 
yes I have compiled ectract_gpu successfully.
I think it's a path problem.
Did you have  modify the Ubuntu "etc/profile“  add the "./extract_gpu" path?

**Comment by wanglimin** [comment]
Now you just need to copy the extract_gpu into your current folder and it will work properly.

**Comment by Jangol** [comment]
@wanglimin 
Thank you ,but I got anthoer problem.

/usr/local/MATLAB/R2013b/bin/glnxa64/libtiff.so.5: no version information available (required by /usr/local/lib/libopencv_highgui.so.2.4)

**Comment by wanglimin** [comment]
It should be your opencv problem. I did not encounter this problem before.

**Comment by Jangol** [comment]
Could you tell me your  ubuntu ,gcc/g++ and matlab version.
Thank you .

**Comment by wanglimin** [comment]
Ubuntu 14.04, matlab 2013a, gcc4.8.2

**Comment by Jangol** [comment]
@wanglimin 
Thanks！
Whether the  RGB & Flow images  created by the dense-folw tool need to rename for train the net.
