### ISSUE TITLE
optimized conv cudnn

### ISSUE THREAD

**Issue by antran89** [yjxiong/caffe#40]
Hi @yjxiong,
I am a problem with speed of running cuhk-caffe. I update caffe with your repo few days ago, and I build Caffe successfully, but running speed at testing time is quite slow. It is slower than previous version in December 2015. One thing that I notice is that there are many messages from Caffe as bellow:

```
I0202 15:18:48.506283 21248 cudnn_conv_layer.cpp:179] Optimized cudnn conv
```

I hope to receive some feedback from you.
Thank you.

**Comment by yjxiong** [comment]
Thanks for you spotting the problem! Can you provide me your running setting?

The line you see means that the framework is trying to find the best cuDNN convolution setting for your device. It should appear only once at startup. Since you see this many times, I suspect there might be a bug.

**Comment by antran89** [comment]
Hi @yjxiong,
I write my own Python testing script, it is just a normal Python testing script. I suspect that it is a general problem.
The script file is in [this link](https://gist.github.com/antran89/391cf772f532887ef6a4). 
If anything I can do, please tell me.

**Comment by yjxiong** [comment]
Thanks. looking into it.

**Comment by yjxiong** [comment]
Hi @antran89 , I cannot see the content of your function `classify_video.VideoTemporalPrediction()`. Are you changing the input shape for each video? If so, it is expected to trigger the cuDNN stuff which outputs the string you saw.

If you do not want this to happen, please try change 
https://github.com/yjxiong/caffe/blob/action_recog/src/caffe/layers/cudnn_conv_layer.cpp#L294

from 
`if (prev_bottom_shapes_[i] == bottom[i]->shape()) continue;`
to
`if (!prev_bottom_shapes_[i].empty()) continue;`
It should be OK then.

**Comment by antran89** [comment]
@yjxiong Thank you so much. I just figured out that I also changed input shape each video compared to the model prototxt file.
Thank you so much.
