### ISSUE TITLE
train_action_recognition_flow.sh and _rgb.sh not working

### ISSUE THREAD

**Issue by Chuseuiti** [yjxiong/caffe#42]
I have installed caffe previously and I can run all the  ipynb examples, however I can not get this to work, as I can not find where is that folder for caffe:

mpirun was unable to launch the specified application as it could not find an executable:

Executable:  
Node: SATDLS

while attempting to start process rank 0.

4 total processes failed to start
./train_action_recognition_flow.sh: 5: ./train_action_recognition_flow.sh: cmake_build/install/bin/caffe: not found

**Comment by yjxiong** [comment]
If you followed the instructions in the README.md (use CMake to compile the binary), this folder `cmake_build` should be in the dir where you put the codebase.

Please note you need the code in THIS repo to enable the MPI related functions.

**Comment by Chuseuiti** [comment]
The name of the folder that is created was build and not cmake_build, changing that I was able to run it thanks

**Comment by yjxiong** [comment]
Good to know you have resolved the problem.  Closing this issue.
