### ISSUE TITLE
python demo code

### ISSUE THREAD

**Issue by mathrho** [yjxiong/caffe#44]
Since Caffe uses BGR image format, and cv2.imread from OpenCV by default loads image in BGR format, we should not reorder the channels again?
[http://github.com/yjxiong/caffe/blob/action_recog/action_python/VideoSpatialPrediction.py#L62](http://github.com/yjxiong/caffe/blob/action_recog/action_python/VideoSpatialPrediction.py#L62)

**Comment by yjxiong** [comment]
good point. I will look into this.

**Comment by yjxiong** [comment]
Hi @mathrho ,

Thanks for spotting the problem. I have fixed this in 4f99d7e7efaa6cefe096f05e288548292f482687
