### ISSUE TITLE
better performance in reading images from disk

### ISSUE THREAD

**Issue by antran89** [yjxiong/caffe#49]
Hi @yjxiong 
I have a question to ask your guys here. I run very deep two-stream cnn on my data, but I do not know why my caffe is reading images from disk very slow. Most of the time spends on reading from disk with unreasonable proportional (about 1s computing and 8s idle, might be reading images from disks as illustrated in the image). Is is an expected behavior? Or a bug? T
![selection_001](https://cloud.githubusercontent.com/assets/2399449/13287837/f6359240-db43-11e5-8c49-e70eb19c3807.png)
Best regards,

**Comment by yjxiong** [comment]
Hi @antran89 ,

If you are running with a HDD, this might happen. If the training runs faster than the HDD reading speed (reading a lot of small image files can be very slow), the system will be mostly waiting for IO.

Two possible solutions: 
1. Use SSD which increases maximal IO throughput.
2. If the dataset can fit into memory, just wait a while after the file system caches the whole dataset.

**Comment by antran89** [comment]
Hi @yjxiong 
About number 2, ucf101 is too big for fitting into memory. If I set smaller batchsize, would it be faster in term of reading small image files from disks. Any caches? thanks

**Comment by yjxiong** [comment]
No I am afraid. Maybe @wanglimin has some idea on cache the UCF101 dataset.

**Comment by wanglimin** [comment]
From my own experience, UCF101is not a problem for our server (our memory 128 GB). The size of ucf101 is around 30GB, and I think it can be cached in the memory after the first epoch.

**Comment by antran89** [comment]
Thank you. The dataset cannot be fitted into memory of my workstation.

**Comment by antran89** [comment]
Hi,
I have noticed that reading flow images from disk is slower than reading normal RGB image. Do you have any intuition why? Although it has more images to load, it should not take much more time than reading normal RGB frames. Your feedback is helpful for me to look at the code. Thanks.
