### ISSUE TITLE
Is it model or data parallel implementation?

### ISSUE THREAD

**Issue by erogol** [yjxiong/caffe#5]
Please note somewhere the details of your parallelization. I guess (sorry if I am blind), in the referred paper as well, no pointer to implementation

**Comment by yjxiong** [comment]
It's basically data parallel. We added some workaround to avoid heavy communication in synchronizing fully connected layers. These are described in the original tech report. 
But thanks for the reminder! I will add some descriptions in README.

**Comment by yjxiong** [comment]
noted in the repo description. closing.
