### ISSUE TITLE
Cannot download pre-trained models for action recognition git hash/commit

### ISSUE THREAD

**Issue by chubchubcharles** [yjxiong/caffe#53]
Hi yjxiong,

I am new to Caffe, and I am trying to download the pre-trained models on this [page](https://github.com/yjxiong/caffe/tree/action_recog/models/action_recognition), but I received an error 404 not found. 

I followed the instructions on the [Caffe Model Zoo](http://caffe.berkeleyvision.org/model_zoo.html) and tried the following command in your project directory:

`./scripts/download_model_from_gist.sh d26b3b8b8eec182a27ce9871752fedd374b63650 ./models/action_recognition/`

Output:

> Downloading Caffe model info to ./models/action_recognition//d26b3b8b8eec182a27ce9871752fedd374b63650 ...
> --2016-03-08 16:43:12--  https://gist.github.com/d26b3b8b8eec182a27ce9871752fedd374b63650/download
> ....
> [unnecessary error info messages]
> ....
> Proxy request sent, awaiting response... 404 Not Found
> 2016-03-08 16:43:13 ERROR 404: Not Found.
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> Done

Is the git hash for the spatial and temporal models incorrect? Or have I used the incorrect commands?
Thank you in advance!

**Comment by yjxiong** [comment]
Please note that the page you link is not a gist. Just follow the download links provided on that page you will get the pretrained models.
