### ISSUE TITLE
请问在net.cpp中的梯度同步问题

### ISSUE THREAD

**Issue by DL-Practise** [yjxiong/caffe#54]
您好。感谢你对多机多卡caffe的共享。目前我在看源码的时候遇到一个小小的困惑，就是在net.cpp中的BackwardFromTo方法中，完成backward运算之后需要对所有GPU的梯度做一个合并操作，即代码“caffe_iallreduce(this->params_[n]->mutable_cpu_diff(),this->params_[n]->count());”我的疑问是改代码中为什么会使用cpu_diff来合并，运算过程中不是把梯度存在gpu_diff中吗？没有看到有哪个地方是吧gpu_dff拷贝到cpu_diff中的。期盼您的解答，谢谢！

**Comment by yjxiong** [comment]
- 调用mutable_cpu_diff()时Blob会自动将gpu数据同步到cpu。
- MPI的cuda allreduce会阻塞GPU上其他运算，而使用cpu上异步allreduce则只需要将数据传回cpu mem。进程间通信的时间可以和计算时间重叠，提高性能。

**Comment by DL-Practise** [comment]
非常感谢您及时的回复，解答了我心中的困惑。

**Comment by Jangol** [comment]
@cjnewstar111 

你好！我刚开始关注深度学习行为识别的研究，最经在调试这个例子，希望能想你请教。QQ182193819
谢谢！
