### ISSUE TITLE
Parallel training speed is too slow

### ISSUE THREAD

**Issue by knsong** [yjxiong/caffe#55]
Hi, @yjxiong 
     I'm using your openmpi based caffe for parallel training. I noticed that when I was running examples of mnist on 2 nodes in a parallel manner, the train  speed was much slower than that of just 1 node. The "Model Synchronization Communication time " was 0.14s or so.
    In the lenet_parallel_solver.prototxt, I just modified device_id: [0, 0](cause I have only 1 GPU on each node).
    And my openmpi-1.8.8 was built  with CUDA-aware support.
    My 2 nodes was connected using SSH.
    Is there something wrong I had made?
   Anyway, Thanks a lot for your work!

**Comment by yjxiong** [comment]
Please note that out implementation still uses synchronized version of
distributed SGD, while it will by all means try to overlap the
communication time into the computation time.

However, the computation time of LeNet is too little to overlap the
communication cost. It is expected you will observe some overhead.

Another thing deciding the training performance is the inter-connect speed.
Common EtherNet may not fit the transmission and delay requirement for fast
training. People have been using Infiniband to achieve optimal performance.

Anyway, this communication overhead will be relatively lower when using
large CNN models. And if you don't want to use Infiniband, you can still
use the code on one Multi-GPU nodes. The intra-node communication overhead
is way less than between nodes. Thus you will obtain almost linear
acceleration with large models.

On Sat, Mar 12, 2016 at 4:36 PM, Dale notifications@github.com wrote:

> Hi, @yjxiong https://github.com/yjxiong
> I'm using your openmpi based caffe for parallel training. I noticed that
> when I was running examples of mnist on 2 nodes in a parallel manner, the
> train speed was much slower than that of just 1 node. The "Model
> Synchronization Communication time " was 0.14s or so.
> In the lenet_parallel_solver.prototxt, I just modified device_id: 0, 0
> http://cause%20I%20have%20only%201%20GPU%20on%20each%20node.
> And my openmpi-1.8.8 was built with CUDA-aware support.
> My 2 nodes was connected using SSH.
> Is there something wrong I had made?
> Anyway, Thanks a lot for your work!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/55.

## 

熊元骏
Xiong, Yuanjun

Department of Information Engineering,
The Chinese University of Hong Kong.

E-mail: bitxiong@gmail.com
Mobile: +852 54282253
Mainland China Mobile: +86 147 1430 8814
Address: SHB703, The Chinese University of Hong Kong.
              Shatin, N.T, Hong Kong.

**Comment by knsong** [comment]
That helps me a lot! Thanks!

**Comment by yjxiong** [comment]
Closing this issue. Please feel free to reopen it should you meet other problems.
