### ISSUE TITLE
action_python run error

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#57]
Hi! @wanglimin @yjxiong 

When I run the action_python demo.py script , I got a problem like this:

[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 538739211
I0316 11:12:52.415251  3143 cudnn_conv_layer.cpp:179] Optimized cudnn conv
Traceback (most recent call last):
  File "demo.py", line 74, in <module>
    main()
  File "demo.py", line 53, in main
    start_frame)
  File "/home/gnss/deeplearing/caffe/action_python/VideoTemporalPrediction.py", line 85, in VideoTemporalPrediction
    prediction[:, span] = np.transpose(output[feature_layer])
KeyError: 'fc8-2'

Hope your help !
Thank you !

**Comment by mkhademi** [comment]
@Jangol How did you solve this problem? I get the same error. Thanks!
@wanglimin @yjxiong I appreciate if you guys can help too!

I do not see a fc8-2 layer in prototxt file. There is a fc8-1 in temporal and fc8 in spatial prototxt files!

**Comment by chuckcho** [comment]
If you had `fc8-1` (the final fully-connected layer) in temporal net, this should be `fc8-1`.

**Comment by mkhademi** [comment]
Thanks @chuckcho for your reply! I renamed the layers to fc8 in both temporal and spatial prototxt files to be consistent. Also modified the feature-layer parameter in demo.py to fc8 and the error was resolved!

**Comment by chuckcho** [comment]
Glad to know the issue was resolved. :+1:
