### ISSUE TITLE
硬件配置

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#58]
Hi @yjxiong  @wanglimin 

我目前只有一块4G显存的GTX 970 显卡，在跑action_python demo,py 时内存不足，想问下有解决的办法吗？后面想更换自己的数据训练，一块显卡能跑吗？

**Comment by nhe150** [comment]
2 GPU each will occupy 500MB memory.

**Comment by yjxiong** [comment]
For training, you can try lower the `batch_size` setting and increase the `iter_size` to still achieve the same effective batchsize. 

For inference, 4GB display mem is pretty much enough for running one frame at a time. Please check your settings.

**Comment by Jangol** [comment]
Hi1
@yjxiong @wanglimin 

减小batch_size的值，运行demo.py ,出现下面错误：

[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 538700084
I0317 17:06:43.484580  3014 cudnn_conv_layer.cpp:179] Optimized cudnn conv

得不到运行结果。

**Comment by yjxiong** [comment]
I can see no error message. Please make sure the program is running on the
GPU.

On Thursday, March 17, 2016, Jangol notifications@github.com wrote:

> Hi1
> @yjxiong https://github.com/yjxiong @wanglimin
> https://github.com/wanglimin
> 
> 减小batch_size的值，运行demo.py ,出现下面错误：
> 
> [libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading
> dangerously large protocol message. If the message turns out to be larger
> than 2147483647 bytes, parsing will be halted for security reasons. To
> increase the limit (or to disable these warnings), see
> CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
> [libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total
> number of bytes read was 538700084
> I0317 17:06:43.484580 3014 cudnn_conv_layer.cpp:179] Optimized cudnn conv
> 
> 得不到运行结果。
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/58#issuecomment-197778405

## 

熊元骏
Xiong, Yuanjun

Department of Information Engineering,
The Chinese University of Hong Kong.

E-mail: bitxiong@gmail.com
Mobile: +852 54282253
Mainland China Mobile: +86 147 1430 8814
Address: SHB703, The Chinese University of Hong Kong.
              Shatin, N.T, Hong Kong.

**Comment by Jangol** [comment]
Hi!
@yjxiong 
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message. If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons. To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 538700084

这种警告是什么原因呢？

**Comment by yjxiong** [comment]
It's due to the extraordinary size of the VGG model file. No harm.

On Friday, March 18, 2016, Jangol notifications@github.com wrote:

> Hi!
> @yjxiong https://github.com/yjxiong
> [libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading
> dangerously large protocol message. If the message turns out to be larger
> than 2147483647 bytes, parsing will be halted for security reasons. To
> increase the limit (or to disable these warnings), see
> CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
> [libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total
> number of bytes read was 538700084
> 
> 这种警告是什么原因呢？
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/58#issuecomment-198167697

## 

熊元骏
Xiong, Yuanjun

Department of Information Engineering,
The Chinese University of Hong Kong.

E-mail: bitxiong@gmail.com
Mobile: +852 54282253
Mainland China Mobile: +86 147 1430 8814
Address: SHB703, The Chinese University of Hong Kong.
              Shatin, N.T, Hong Kong.
