### ISSUE TITLE
how to measure accuracy on validation set?

### ISSUE THREAD

**Issue by nhe150** [yjxiong/caffe#59]
I have used
build/install/bin/caffe test   --model=models/action_recognition/vgg_16_flow_train_val_fast.prototxt     --weights=cuhk_action_recognition_16_split1_flow_iter_11000.caffemodel --iterations 100

Not sure about iteration number which one to use?
Is this been used for the published accuracy for optical_flow net?

**Comment by yjxiong** [comment]
Please use the provided MATLAB or Python scripts to produce video-level predictions, on which the accuracy is evaluated.

See

https://github.com/yjxiong/caffe/tree/action_recog/action_matlab

or 

https://github.com/yjxiong/caffe/tree/action_recog/action_python

Caffe's test utility will produce the accuracy using only one frame (the mid-time one) per-video.

**Comment by nhe150** [comment]
thank you very much.
