### ISSUE TITLE
Temporal net

### ISSUE THREAD

**Issue by kli-casia** [yjxiong/caffe#6]
Hi, @yjxiong 
I use your matlab test code with the temporal caffe model you provided to test the accuray of UCF split1,2,3
The result is 84%,86.2%,85.5%.
In your paper the result is 85.7%,88.2%,87.4%
I use your denseflow_gpu code to extrace optical flow like this './denseFlow_gpu -f myvideo.avi -x tmp/flow_x -y tmp/flow_y -i tmp/image -b 20 -t 1 -d 0 -s 1 '

**Comment by wanglimin** [comment]
I have just tested split1 and my result is 85.72%.  How did you fuse the 25
predictions for each video?

Limin

On Sun, Aug 30, 2015 at 10:47 AM, Kai Li notifications@github.com wrote:

> Hi, @yjxiong https://github.com/yjxiong
> I use your matlab test code with the temporal caffe model you provided to
> test the accuray of UCF split1,2,3
> The result is 84%,86.2%,85.5%.
> In your paper the result is 85.7%,88.2%,87.4%
> I use your denseflow_gpu code to extrace optical flow like this
> './denseFlow_gpu -f myvideo.avi -x tmp/flow_x -y tmp/flow_y -i tmp/image -b
> 20 -t 1 -d 0 -s 1 '
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/6.

## 

Limin Wang
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by kli-casia** [comment]
@wanglimin 
I use your matlab test code, just added two lines of code

```
temporal_prediction = VideoTemporalPrediction(video_name, mean_file, net);
prediction=mean(temporal_prediction,2);
[~,prediction_label]=max(prediction);

```

**Comment by wanglimin** [comment]
This should be right.

I am not sure what is wrong with your test process. One possible reason is
that the decoding problem of opencv for video, which may lead to difference
in optical flow calculation.

Limin

On Sun, Aug 30, 2015 at 10:14 PM, Kai Li notifications@github.com wrote:

> @wanglimin https://github.com/wanglimin
> I use your matlab test code, just added two lines of code
> 
> temporal_prediction = VideoTemporalPrediction(video_name, mean_file, net);
> prediction=mean(temporal_prediction,2);
> [~,prediction_label]=max(prediction);
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/6#issuecomment-136144514.

## 

Limin Wang
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by kli-casia** [comment]
Thank you. I will check it
