### ISSUE TITLE
action_python 

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#60]
Hi! 
@yjxiong 

demo.py 运行得到fused_pred 矩阵，我理解每一项为输入测试数据分类为101种行为的概率，不知道是否正确？我从paper（Towards Good Practices for Very Deep Two-Stream ConvNets）中理解，
fused_pred得到概率作为最后的识别率，但是这只是一个视频的数据的结果，想问下paper中的的结果是怎么得到呢？期待您的回复，非常感谢！

**Comment by yjxiong** [comment]
Accuracy reported is obtained by comparing the video-level predictions with groundtruth labels of the videos, average over all classes. Generally, its the mean of diagonal elements of the confusion matrix.
