### ISSUE TITLE
video_data_layer

### ISSUE THREAD

**Issue by liu09114** [yjxiong/caffe#61]
在VideoData层中，训练数据是这样的：
ucf101_rgb_img/WallPushups/v_WallPushups_g21_c06 111 98，
111也就是从这个视频提取了111 frames（RGB或者optical flow），
我想了解下这个层的一些参数是什么意思。
new_length、new_segments表示什么？
特别是batch_size指的是一个iteration的frames的数目？还是指的video的数目？拿训练数据train_rgb_split1.txt举例来说就是：batch_size是指的111中的多少幅图像，还是train_rgb_split1.txt中的batch_size数目的行数？
另外想问下要做real-time的action recognition，您有什么建议么？
希望您能回答一下，谢谢了。

**Comment by wanglimin** [comment]
@liu09114 

111是这个视频的帧数，98是这个视频的标签。
new_length表示每次训练你需要抽多少帧，目前spatial net是1帧，temporal net是10帧。
new_segment这个参数目前没有用，请设定为1。
batch_size指的是video的数目，不是帧的数目。

今年我们cvpr有一篇paper就是关于real time action recognition, 过一段时间应该camera ready就会放出来：

Real-time Action Recognition with Enhanced Motion Vector CNNs

利民

**Comment by liu09114** [comment]
@wanglimin 
明白了，谢谢。
希望能尽快放出这篇文章来。

**Comment by Jangol** [comment]
Hi！
@wanglimin 

我只有一块4G显存的显卡，batch_size=22，内存不足，我把batch_size设置为“1”，想问下，哪些参数需要更改，训练效果可接近您文章中4GPU的识别率？

非常感谢您的分享，期待您的回复！

**Comment by liu09114** [comment]
@wanglimin 
name: "CUHK_Action_SpatialNet"
layer {
  name: "data"
  type: "VideoData"
  top: "data"
  top: "label_local"
  video_data_param {
    source: "examples/action_recognition/dataset_file_examples/train_rgb_split1.txt"
    batch_size: 16
    new_width: 340
    new_height: 256
    new_length: 1
    num_segments: 1
    modality: RGB
  }
  transform_param{
    crop_size: 224
    mirror: true
    fix_crop: true
    multi_scale: true
    max_distort: 1
    scale_ratios: [1,.875,.75,.66]
    mean_value: [104, 117, 123]
  }
  include: { phase: TRAIN }
}
还是有些不明白，比如上面这个配置，进行一次iteration的图片量是多少呢？16张？还是要经过transform后扩充到更多呢？
