### ISSUE TITLE
train _param problem

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#62]
Hi！
@wanglimin

我只有一块4G显存的显卡，batch_size=22，内存不足，我把batch_size设置为“1”，想问下，哪些参数需要更改，训练效果可接近您文章中4GPU的识别率？

非常感谢您的分享，期待您的回复！

**Comment by wanglimin** [comment]
那你在solver里面的需要设置iter_size: 256

**Comment by Jangol** [comment]
这样做的依据是什么呢？

**Comment by wanglimin** [comment]
因为有效的batch_size = num_gpu \* iter_size \* batch_size. 现在你的num_gpu=1, batch_size =1, 你要达到有效batch_size为256，只能把iter_size设置为256.
