### ISSUE TITLE
Pre-extracted optical flow data: Are there some videos missing from ucf101_flow_img_tvl1_gpu.zip?

### ISSUE THREAD

**Issue by victorhcm** [yjxiong/caffe#64]
Hi there!

I was testing for the first split using your optical flow data, when I noticed that there were a few folders that couldn't be extracted from the zip. Does it comprise the optical flow for all videos?

**Comment by victorhcm** [comment]
Just one more thing, can you provide a checksum for this zip file? I think my file might be corrupted, although I retried to download it using `wget -c` and it says the download has finished.

**Comment by wanglimin** [comment]
@victorhcm 

I think you need to download the flow.zip again from the following link:

http://mmlab.siat.ac.cn/very_deep_two_stream_model/ucf101_flow_img_tvl1_gpu.zip

As our server may not be stable, you should check the file size and the correct size should be around 21G.

Limin

**Comment by victorhcm** [comment]
Thank you, Limin! I'll check it out, it probably was corrupted during download. 

Sorry for bothering you with this; and thank you all again for making this repo available :)
