### ISSUE TITLE
关于编译的一点问题

### ISSUE THREAD

**Issue by MenglaiWang** [yjxiong/caffe#66]
`-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
**-- Boost version: 1.54.0**
-- Found the following Boost libraries:
--   system
--   thread
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
**-- Looking for pthread_create - not found**
-- Looking for pthread_create in pthreads
**-- Looking for pthread_create in pthreads - not found**
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found GFlags: /usr/include
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/libhdf5.so
-- Found LMDB: /usr/include
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB: /usr/include
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy: /usr/include
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 7.0
-- Found cuDNN (include: /usr/local/include, library: /usr/local/lib/libcudnn.so)
-- Added CUDA NVCC flags for: sm_35
-- OpenCV found (/usr/local/share/OpenCV)
-- Found Atlas: /usr/include
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.6", minimum required is "2.7")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7")
-- Found NumPy: /usr/lib/python2.7/dist-packages/numpy/core/include (found suitable version "1.8.2", minimum required is "1.7.1")
-- NumPy ver. 1.8.2 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
**-- Could NOT find Boost**
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6")
-- Found MPI_C: /usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so
-- Found MPI_CXX: /usr/lib/libmpi_cxx.so;/usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so
**-- Python interface is disabled or not all required dependecies found. Building without it...**
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- Found Git: /usr/bin/git (found version "1.9.1")

--  Caffe Configuration Summary 
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   v0.9999-1553-gc54adf0-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release

--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF

-- Dependencies:
--   BLAS              :   Yes (Atlas)
**--   Boost             :   Yes (ver. 1.54)**
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   Snappy            :   Yes (ver. 1.1.0)
--   LevelDB           :   Yes (ver. 1.15)
--   OpenCV            :   Yes (ver. 2.4.12)
--   CUDA              :   Yes (ver. 7.0)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35
--   cuDNN             :   Yes

-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.6)
--   config_file       :   /home/zyy/workspace/wangml/caffe-action/.Doxyfile

-- Install:
--   Install path      :   /home/zyy/workspace/wangml/caffe-action/build/install

-- Configuring done
-- Generating done
-- Build files have been written to: /home/zyy/workspace/wangml/caffe-action/build
`

@wanglimin
作者你好，感谢你分享你的代码，我编译的时候遇到了一些问题，但是一直没解决，希望您能抽时间帮我看看，不胜感激！
运行环境：
openmpi 1.8.8
python 2.7
matlab 2014a
opencv  2.4.12
上面是我`cmake .. -DUSE_MPI=ON`得到的结果，涂黑的地方是我的问题。1、Boost，后面编译都知道我装的是1.5.4版本，为什么前面会提示找不到呢？这个会不会对后续有影响？2、python和matlab编译，因为我对cmake不太熟，我没太明白怎么用cmake手动编译matcaffe和pycaffe。而且因为matcaffe和pycaffe都没有编译成功，所以后面我运行你的两个demo的时候，都出现了找不到caffe的情况。

**Comment by yjxiong** [comment]
To use Python interfaces, you need Boost 1.55.
If 1.54 is already installed, first `apt get remove libboost-all-dev` then `apt-get install libboost1.55-all-dev`.

Once cmake finds required libraries for pycaffe and matcaffe, it will automatically compile them. No need to manually enable them.

**Comment by MenglaiWang** [comment]
@yjxiong The problem is solved. I am really grateful for your reply so quickly !
