### ISSUE TITLE
ERROR: undefined reference to `cv::VideoCapture

### ISSUE THREAD

**Issue by yi374700** [yjxiong/caffe#67]
[ 91%] Building CXX object tools/CMakeFiles/caffe.bin.dir/caffe.cpp.o
Linking CXX executable caffe
../lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
../lib/libcaffe.so: undefined reference to`cv::VideoCapture::~VideoCapture()'
../lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
../lib/libcaffe.so: undefined reference to`cv::VideoCapture::get(int) const'
../lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
../lib/libcaffe.so: undefined reference to`cv::VideoCapture::VideoCapture(cv::String const&)'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/caffe] Error 1
make[1]: **\* [tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: **\* [all] Error 2

After following the instruction in README, I run make&&make install in bulid. However, i got the info above.
I have add the opencv_videoio in Makefile but it still get wrong. How to fix it? Thanks.

**Comment by yjxiong** [comment]
Sorry we accidentally merged some experimental codes into the main branch. It has been pruned. Please update the git repo and try again.
