### ISSUE TITLE
mpirun problem

### ISSUE THREAD

**Issue by MenglaiWang** [yjxiong/caffe#68]
@yjxiong 
I have compiled mpi and caffe successfully, and I can run your python demo as well. However, I can't get trainning to work. 
Since I have two 6G GPUs ,I run this script:
`
# !/usr/bin/env sh

GOOGLE_LOG_DIR=models/action_recognition/log \
mpirun -np 2 \
 build/install/bin/caffe train \
--solver=models/action_recognition/vgg_16_rgb_solver.prototxt \
--weights=data/vgg_16_action_rgb_pretrain.caffemodel
`
and it comes like this:
`I0413 16:17:41.867636  2911 solver.cpp:363] Solving CUHK_Action_SpatialNet
I0413 16:17:41.867724  2911 solver.cpp:364] Learning Rate Policy: step
I0413 16:17:42.153273  2911 solver.cpp:335] Model Synchronization Communication time 0.285497 second
I0413 16:17:42.297106  2911 solver.cpp:335] Model Synchronization Communication time 0.139519 second
I0413 16:17:42.297143  2911 solver.cpp:428] Iteration 0, Testing net (#0)
**\* Aborted at 1460535462 (unix time) try "date -d @1460535462" if you are using GNU date ***
PC: @     0x7f7b2edf5ff0 (unknown)
**\* SIGSEGV (@0x73f160000) received by PID 2911 (TID 0x7f7a914f8700) from PID 1058406400; stack trace: ***
    @     0x7f7b2ed94d40 (unknown)
    @     0x7f7b2edf5ff0 (unknown)
    @     0x7f7b2f73c779 (unknown)
    @     0x7f7b06b6785d (unknown)
    @     0x7f7b079d1c9c (unknown)
    @     0x7f7b079c456c (unknown)
    @     0x7f7b05ca72e7 (unknown)
    @     0x7f7b05cad6ef (unknown)
    @     0x7f7b2f6a20c9 (unknown)
    @     0x7f7b306bdd2e caffe::MPIComm::DispatchJob()
    @     0x7f7b306bdfdc caffe::MPIComm::ThreadFunc()
    @     0x7f7b2e94ee7a (unknown)
    @     0x7f7b2e72d182 start_thread
    @     0x7f7b2ee5847d (unknown)
    @                0x0 (unknown)
**\* Aborted at 1460535462 (unix time) try "date -d @1460535462" if you are using GNU date ***
PC: @     0x7f92b3996ff0 (unknown)
**\* SIGSEGV (@0x73f160000) received by PID 2912 (TID 0x7f9215df9700) from PID 1058406400; stack trace: ***
    @     0x7f92b3935d40 (unknown)
    @     0x7f92b3996ff0 (unknown)
    @     0x7f92b42dd779 (unknown)
    @     0x7f928b69b85d (unknown)
    @     0x7f928c505c9c (unknown)
    @     0x7f928c4f856c (unknown)
    @     0x7f928a7d82e7 (unknown)
    @     0x7f928a7de6ef (unknown)
    @     0x7f92b42430c9 (unknown)
    @     0x7f92b525ed2e caffe::MPIComm::DispatchJob()
    @     0x7f92b525efdc caffe::MPIComm::ThreadFunc()
    @     0x7f92b34efe7a (unknown)
    @     0x7f92b32ce182 start_thread
    @     0x7f92b39f947d (unknown)
    @                0x0 (unknown)

*_mpirun noticed that process rank 0 with PID 2911 on node zyy-All-Series exited on signal 11 (Segmentation fault).
*_
`

And when I run  `mpirun -np 1`, it's OK ! I don't what went wrong. Have you ever met this problem?

**Comment by yjxiong** [comment]
In many cases I found this may be due to incorrectly linked MPI libraries.  
Please run `ldd caffebuild/install/bin/caffe | grep` to see which MPI is linked against the caffe's binary. 
And make sure the linked ones are from the same MPI version with which the binary is compiled.

**Comment by MenglaiWang** [comment]
@yjxiong 
I am sorry that I am unfamiliar with the `grep`command. So I ran`ldd caffe/build/install/bin/caffe` , I guess what you wanna see is this ?
`libmpi_cxx.so.1 => /usr/lib/libmpi_cxx.so.1 (0x00007ff66e531000)
        libmpi.so.1 => /usr/lib/libmpi.so.1 (0x00007ff66e1b0000)
`
my mpi version is 1.8.8

**Comment by yjxiong** [comment]
If the MPI is correctly linked, the next thing to check is the CUDA support
of openmpi. It's by default turned off. One needs to switch it on before
compiling MPI libraries.

On Wednesday, April 13, 2016, Menglai Wang notifications@github.com wrote:

> @yjxiong https://github.com/yjxiong
> I am sorry that I am unfamiliar with the grepcommand. So I ranldd
> caffe/build/install/bin/caffe , I guess what you wanna see is this ?
> libmpi_cxx.so.1 => /usr/lib/libmpi_cxx.so.1 (0x00007ff66e531000)
> libmpi.so.1 => /usr/lib/libmpi.so.1 (0x00007ff66e1b0000)
> 
> my mpi version is 1.8.8
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/68#issuecomment-209354472

## 

熊元骏
Xiong, Yuanjun

Department of Information Engineering,
The Chinese University of Hong Kong.

E-mail: bitxiong@gmail.com
Mobile: +852 54282253
Mainland China Mobile: +86 147 1430 8814
Address: SHB703, The Chinese University of Hong Kong.
              Shatin, N.T, Hong Kong.

**Comment by MenglaiWang** [comment]
I compiled MPI in the following steps:
`
shell$ ./configure --with-cuda

sudo make all install

sudo gedit /etc/profile

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

source /etc/profile
`
Is that all right?

**Comment by yjxiong** [comment]
The steps look good to me.

I cannot tell where the problem is from current information. Assuming you have completely followed the instructions in README, I can only give you some suggestions:
1. Rebuild Caffe after removing all stuffs in `cmake_build`
2. If there are multiple MPI versions installed on the machine, make sure you are using the one you compiled with CUDA support.

The reason I insist on checking MPI is that you can run single process mode without problem. Under single process mode, whether you use mpirun or not, it will not call any MPI collectives.

**Comment by MenglaiWang** [comment]
I have only one MPI version,namely 1.8.8. And I have already rebuild caffe after removing `cmake_build`,but it still comes out  the same mistake. I'am considering reinstalling mpi. Or would you please tell me what version of MPI you are using?

**Comment by yjxiong** [comment]
I have tried 1.8.7 and 1.8.10, both working properly

On Wed, Apr 13, 2016 at 7:10 PM, Menglai Wang notifications@github.com
wrote:

> I have only one MPI version,namely 1.8.8. And I have already rebuild caffe
> after removing cmake_build,but it still comes out the same mistake. I'am
> considering reinstalling mpi. Or would you please tell me what version of
> MPI you are using?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/68#issuecomment-209370565

## 

熊元骏
Xiong, Yuanjun

Department of Information Engineering,
The Chinese University of Hong Kong.

E-mail: bitxiong@gmail.com
Mobile: +852 54282253
Mainland China Mobile: +86 147 1430 8814
Address: SHB703, The Chinese University of Hong Kong.
              Shatin, N.T, Hong Kong.

**Comment by MenglaiWang** [comment]
@yjxiong 
After reinstall 1.8.7, It goes right !!!

**Comment by yjxiong** [comment]
Good to hear that. Enjoy your training:)

**Comment by geekvc** [comment]
I run this script:
```sh
#!/usr/bin/env sh
GLOG_logtostderr=1 \
mpirun -np 4 \
../../build/tools/caffe train \
--solver=vgg_16_flow_solver.prototxt \
--weights=vgg_16_action_flow_pretrain.caffemodel
```
and it comes like this:
```sh
I0719 16:58:56.462492 22242 layer_factory.hpp:74] Creating layer data
I0719 16:58:56.462520 22242 net.cpp:96] Creating Layer data
I0719 16:58:56.462532 22242 net.cpp:415] data -> data
I0719 16:58:56.462554 22242 net.cpp:415] data -> label_local
I0719 16:58:56.462571 22242 net.cpp:160] Setting up data
I0719 16:58:56.463037 22242 video_data_layer.cpp:34] Opening file: dataset_file_examples/train_flow_split1.txt
I0719 16:58:56.468557 22244 video_data_layer.cpp:50] A total of 9537 videos.
E0719 16:58:56.468622 22244 io.cpp:377] Could not load file ucf101_flow_img_tvl1_gpu/WallPushups/v_WallPushups_g21_c06/flow_x_0055.jpg or ucf101_flow_img_tvl1_gpu/WallPushups/v_WallPushups_g21_c06/flow_y_0055.jpg
F0719 16:58:56.468633 22244 video_data_layer.cpp:76] Check failed: ReadSegmentFlowToDatum(lines_[lines_id_].first, lines_[lines_id_].second, offsets, new_height, new_width, new_length, &datum, name_pattern_.c_str())
*** Check failure stack trace: ***
I0719 16:58:56.469640 22242 video_data_layer.cpp:50] A total of 9537 videos.
E0719 16:58:56.469688 22242 io.cpp:377] Could not load file ucf101_flow_img_tvl1_gpu/WallPushups/v_WallPushups_g21_c06/flow_x_0034.jpg or ucf101_flow_img_tvl1_gpu/WallPushups/v_WallPushups_g21_c06/flow_y_0034.jpg
F0719 16:58:56.469698 22242 video_data_layer.cpp:76] Check failed: ReadSegmentFlowToDatum(lines_[lines_id_].first, lines_[lines_id_].second, offsets, new_height, new_width, new_length, &datum, name_pattern_.c_str())
*** Check failure stack trace: ***
    @     0x7f72733e9daa  (unknown)
    @     0x7f72733e9ce4  (unknown)
    @     0x7f3b79c2ddaa  (unknown)
    @     0x7f72733e96e6  (unknown)
    @     0x7f3b79c2dce4  (unknown)
    @     0x7f72733ec687  (unknown)
    @     0x7f3b79c2d6e6  (unknown)
    @     0x7f3b79c30687  (unknown)
    @     0x7f727384cabb  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7f3b7a090abb  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7f7273835d39  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f3b7a079d39  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f7273778a83  caffe::Net<>::Init()
    @     0x7f3b79fbca83  caffe::Net<>::Init()
    @     0x7f727377a8c3  caffe::Net<>::Net()
    @     0x7f3b79fbe8c3  caffe::Net<>::Net()
    @     0x7f72737a0710  caffe::Solver<>::InitTrainNet()
    @     0x7f3b79fe4710  caffe::Solver<>::InitTrainNet()
    @     0x7f72737a16e3  caffe::Solver<>::Init()
    @     0x7f3b79fe56e3  caffe::Solver<>::Init()
    @     0x7f72737a18b6  caffe::Solver<>::Solver()
    @           0x40daa0  caffe::GetSolver<>()
    @           0x407559  train()
    @           0x405a56  main
    @     0x7f3b79fe58b6  caffe::Solver<>::Solver()
    @           0x40daa0  caffe::GetSolver<>()
    @           0x407559  train()
    @     0x7f7272397ec5  (unknown)
    @           0x405a56  main
    @           0x40603b  (unknown)
    @     0x7f3b78bdbec5  (unknown)
    @           0x40603b  (unknown)
    @              (nil)  (unknown)
    @              (nil)  (unknown)
```
I have download "ucf101_flow_img_tvl1_gpu" dataset in github, I don't what went wrong. Can you help me solve this problem?
