### ISSUE TITLE
caffe test commond accuracy all zero.

### ISSUE THREAD

**Issue by kli-casia** [yjxiong/caffe#7]
Hi, @wanglimin  @yjxiong 

I use caffe test commond to test the temporal model you provided.

```
~/caffe-action/build/install/bin/caffe test -model vgg_16_flow_train_val_fast.prototxt -weights ~/very-deep-two-stream/wanglimin-model/cuhk_action_temporal_vgg_16_split1.caffemodel   -gpu 0
```

But the accuray all zero. I can't find what's wrong (but the matlab test code works).

```
I0831 20:58:21.425902  5977 caffe.cpp:210] Running for 50 iterations.
I0831 20:58:21.705755  5977 caffe.cpp:234] Batch 0, accuracy = 0
I0831 20:58:21.705826  5977 caffe.cpp:234] Batch 0, loss = 4.56581
I0831 20:58:21.842283  5977 caffe.cpp:234] Batch 1, accuracy = 0
I0831 20:58:21.842308  5977 caffe.cpp:234] Batch 1, loss = 4.57135
I0831 20:58:21.968304  5977 caffe.cpp:234] Batch 2, accuracy = 0
I0831 20:58:21.968328  5977 caffe.cpp:234] Batch 2, loss = 4.56923
I0831 20:58:22.085276  5977 caffe.cpp:234] Batch 3, accuracy = 0
I0831 20:58:22.085300  5977 caffe.cpp:234] Batch 3, loss = 4.56122
I0831 20:58:22.200157  5977 caffe.cpp:234] Batch 4, accuracy = 0.2
I0831 20:58:22.200182  5977 caffe.cpp:234] Batch 4, loss = 4.55828
I0831 20:58:22.312468  5977 caffe.cpp:234] Batch 5, accuracy = 0
I0831 20:58:22.312490  5977 caffe.cpp:234] Batch 5, loss = 4.55105
I0831 20:58:22.422643  5977 caffe.cpp:234] Batch 6, accuracy = 0
I0831 20:58:22.422667  5977 caffe.cpp:234] Batch 6, loss = 4.58159
I0831 20:58:22.533643  5977 caffe.cpp:234] Batch 7, accuracy = 0
I0831 20:58:22.533668  5977 caffe.cpp:234] Batch 7, loss = 4.59634
I0831 20:58:22.646528  5977 caffe.cpp:234] Batch 8, accuracy = 0
I0831 20:58:22.646553  5977 caffe.cpp:234] Batch 8, loss = 4.59047
I0831 20:58:22.761013  5977 caffe.cpp:234] Batch 9, accuracy = 0
I0831 20:58:22.761052  5977 caffe.cpp:234] Batch 9, loss = 4.62319
I0831 20:58:22.877241  5977 caffe.cpp:234] Batch 10, accuracy = 0
I0831 20:58:22.877264  5977 caffe.cpp:234] Batch 10, loss = 4.63062
I0831 20:58:22.992969  5977 caffe.cpp:234] Batch 11, accuracy = 0
I0831 20:58:22.992990  5977 caffe.cpp:234] Batch 11, loss = 4.63736
I0831 20:58:23.105216  5977 caffe.cpp:234] Batch 12, accuracy = 0
I0831 20:58:23.105239  5977 caffe.cpp:234] Batch 12, loss = 4.64331
I0831 20:58:23.216982  5977 caffe.cpp:234] Batch 13, accuracy = 0
I0831 20:58:23.217003  5977 caffe.cpp:234] Batch 13, loss = 4.63844
I0831 20:58:23.328269  5977 caffe.cpp:234] Batch 14, accuracy = 0
I0831 20:58:23.328290  5977 caffe.cpp:234] Batch 14, loss = 4.62079
I0831 20:58:23.436784  5977 caffe.cpp:234] Batch 15, accuracy = 0
I0831 20:58:23.436825  5977 caffe.cpp:234] Batch 15, loss = 4.59784
I0831 20:58:23.547108  5977 caffe.cpp:234] Batch 16, accuracy = 0
I0831 20:58:23.547130  5977 caffe.cpp:234] Batch 16, loss = 4.60577
I0831 20:58:23.658761  5977 caffe.cpp:234] Batch 17, accuracy = 0
I0831 20:58:23.658782  5977 caffe.cpp:234] Batch 17, loss = 4.59781
I0831 20:58:23.770740  5977 caffe.cpp:234] Batch 18, accuracy = 0
I0831 20:58:23.770763  5977 caffe.cpp:234] Batch 18, loss = 4.59607
I0831 20:58:23.882455  5977 caffe.cpp:234] Batch 19, accuracy = 0
I0831 20:58:23.882477  5977 caffe.cpp:234] Batch 19, loss = 4.60705
I0831 20:58:23.993892  5977 caffe.cpp:234] Batch 20, accuracy = 0
I0831 20:58:23.993913  5977 caffe.cpp:234] Batch 20, loss = 4.60775
I0831 20:58:24.102294  5977 caffe.cpp:234] Batch 21, accuracy = 0
I0831 20:58:24.102314  5977 caffe.cpp:234] Batch 21, loss = 4.59202
I0831 20:58:24.209605  5977 caffe.cpp:234] Batch 22, accuracy = 0
I0831 20:58:24.209630  5977 caffe.cpp:234] Batch 22, loss = 4.60682
I0831 20:58:24.318430  5977 caffe.cpp:234] Batch 23, accuracy = 0
I0831 20:58:24.318454  5977 caffe.cpp:234] Batch 23, loss = 4.62756
I0831 20:58:24.424371  5977 caffe.cpp:234] Batch 24, accuracy = 0
I0831 20:58:24.424392  5977 caffe.cpp:234] Batch 24, loss = 4.61974
I0831 20:58:24.530743  5977 caffe.cpp:234] Batch 25, accuracy = 0
I0831 20:58:24.530766  5977 caffe.cpp:234] Batch 25, loss = 4.62237
I0831 20:58:24.637039  5977 caffe.cpp:234] Batch 26, accuracy = 0
I0831 20:58:24.637059  5977 caffe.cpp:234] Batch 26, loss = 4.6219
I0831 20:58:24.744755  5977 caffe.cpp:234] Batch 27, accuracy = 0
I0831 20:58:24.744776  5977 caffe.cpp:234] Batch 27, loss = 4.6247
I0831 20:58:24.852677  5977 caffe.cpp:234] Batch 28, accuracy = 0
I0831 20:58:24.852699  5977 caffe.cpp:234] Batch 28, loss = 4.61173
I0831 20:58:24.960541  5977 caffe.cpp:234] Batch 29, accuracy = 0
I0831 20:58:24.960561  5977 caffe.cpp:234] Batch 29, loss = 4.6213
I0831 20:58:25.068442  5977 caffe.cpp:234] Batch 30, accuracy = 0
I0831 20:58:25.068462  5977 caffe.cpp:234] Batch 30, loss = 4.60979
I0831 20:58:25.175941  5977 caffe.cpp:234] Batch 31, accuracy = 0
I0831 20:58:25.175961  5977 caffe.cpp:234] Batch 31, loss = 4.60837
I0831 20:58:25.282083  5977 caffe.cpp:234] Batch 32, accuracy = 0
I0831 20:58:25.282104  5977 caffe.cpp:234] Batch 32, loss = 4.61826
I0831 20:58:25.388100  5977 caffe.cpp:234] Batch 33, accuracy = 0
I0831 20:58:25.388120  5977 caffe.cpp:234] Batch 33, loss = 4.61304
I0831 20:58:25.494299  5977 caffe.cpp:234] Batch 34, accuracy = 0
I0831 20:58:25.494320  5977 caffe.cpp:234] Batch 34, loss = 4.60632
I0831 20:58:25.600524  5977 caffe.cpp:234] Batch 35, accuracy = 0
I0831 20:58:25.600544  5977 caffe.cpp:234] Batch 35, loss = 4.60945
I0831 20:58:25.706799  5977 caffe.cpp:234] Batch 36, accuracy = 0
I0831 20:58:25.706820  5977 caffe.cpp:234] Batch 36, loss = 4.6146
I0831 20:58:25.812988  5977 caffe.cpp:234] Batch 37, accuracy = 0
I0831 20:58:25.813009  5977 caffe.cpp:234] Batch 37, loss = 4.63083
I0831 20:58:25.919095  5977 caffe.cpp:234] Batch 38, accuracy = 0
I0831 20:58:25.919114  5977 caffe.cpp:234] Batch 38, loss = 4.58947
I0831 20:58:26.025218  5977 caffe.cpp:234] Batch 39, accuracy = 0
I0831 20:58:26.025239  5977 caffe.cpp:234] Batch 39, loss = 4.60846
I0831 20:58:26.133335  5977 caffe.cpp:234] Batch 40, accuracy = 0
I0831 20:58:26.133358  5977 caffe.cpp:234] Batch 40, loss = 4.61726
I0831 20:58:26.241446  5977 caffe.cpp:234] Batch 41, accuracy = 0
I0831 20:58:26.241468  5977 caffe.cpp:234] Batch 41, loss = 4.60415
I0831 20:58:26.349599  5977 caffe.cpp:234] Batch 42, accuracy = 0
I0831 20:58:26.349620  5977 caffe.cpp:234] Batch 42, loss = 4.62642
I0831 20:58:26.457484  5977 caffe.cpp:234] Batch 43, accuracy = 0
I0831 20:58:26.457504  5977 caffe.cpp:234] Batch 43, loss = 4.61726
I0831 20:58:26.565490  5977 caffe.cpp:234] Batch 44, accuracy = 0
I0831 20:58:26.565513  5977 caffe.cpp:234] Batch 44, loss = 4.62254
I0831 20:58:26.674124  5977 caffe.cpp:234] Batch 45, accuracy = 0
I0831 20:58:26.674144  5977 caffe.cpp:234] Batch 45, loss = 4.61613
I0831 20:58:26.781986  5977 caffe.cpp:234] Batch 46, accuracy = 0
I0831 20:58:26.782007  5977 caffe.cpp:234] Batch 46, loss = 4.62502
I0831 20:58:26.888824  5977 caffe.cpp:234] Batch 47, accuracy = 0
I0831 20:58:26.888845  5977 caffe.cpp:234] Batch 47, loss = 4.58574
I0831 20:58:26.995069  5977 caffe.cpp:234] Batch 48, accuracy = 0
I0831 20:58:26.995091  5977 caffe.cpp:234] Batch 48, loss = 4.60927
I0831 20:58:27.101228  5977 caffe.cpp:234] Batch 49, accuracy = 0.2
I0831 20:58:27.101250  5977 caffe.cpp:234] Batch 49, loss = 4.60648
I0831 20:58:27.101258  5977 caffe.cpp:239] Loss: 4.60677
I0831 20:58:27.101277  5977 caffe.cpp:251] accuracy = 0.008
I0831 20:58:27.101294  5977 caffe.cpp:251] loss = 4.60677 (* 1 = 4.60677 loss)
```

**Comment by wanglimin** [comment]
The name of fully connected layer 8 should be fc8 instead of fc8-1. Please
check.

Limin

On Tue, Sep 1, 2015 at 10:04 AM, Kai Li notifications@github.com wrote:

> Hi, @wanglimin https://github.com/wanglimin @yjxiong
> https://github.com/yjxiong
> 
> I use caffe test commond to test the temporal model you provided.
> 
> ~/caffe-action/build/install/bin/caffe test -model vgg_16_flow_train_val_fast.prototxt -weights ~/very-deep-two-stream/wanglimin-model/cuhk_action_temporal_vgg_16_split1.caffemodel   -gpu 0
> 
> But the accuray all zero. I can't find what's wrong (but the matlab test
> code works).
> 
> I0831 20:58:21.425902  5977 caffe.cpp:210] Running for 50 iterations.
> I0831 20:58:21.705755  5977 caffe.cpp:234] Batch 0, accuracy = 0
> I0831 20:58:21.705826  5977 caffe.cpp:234] Batch 0, loss = 4.56581
> I0831 20:58:21.842283  5977 caffe.cpp:234] Batch 1, accuracy = 0
> I0831 20:58:21.842308  5977 caffe.cpp:234] Batch 1, loss = 4.57135
> I0831 20:58:21.968304  5977 caffe.cpp:234] Batch 2, accuracy = 0
> I0831 20:58:21.968328  5977 caffe.cpp:234] Batch 2, loss = 4.56923
> I0831 20:58:22.085276  5977 caffe.cpp:234] Batch 3, accuracy = 0
> I0831 20:58:22.085300  5977 caffe.cpp:234] Batch 3, loss = 4.56122
> I0831 20:58:22.200157  5977 caffe.cpp:234] Batch 4, accuracy = 0.2
> I0831 20:58:22.200182  5977 caffe.cpp:234] Batch 4, loss = 4.55828
> I0831 20:58:22.312468  5977 caffe.cpp:234] Batch 5, accuracy = 0
> I0831 20:58:22.312490  5977 caffe.cpp:234] Batch 5, loss = 4.55105
> I0831 20:58:22.422643  5977 caffe.cpp:234] Batch 6, accuracy = 0
> I0831 20:58:22.422667  5977 caffe.cpp:234] Batch 6, loss = 4.58159
> I0831 20:58:22.533643  5977 caffe.cpp:234] Batch 7, accuracy = 0
> I0831 20:58:22.533668  5977 caffe.cpp:234] Batch 7, loss = 4.59634
> I0831 20:58:22.646528  5977 caffe.cpp:234] Batch 8, accuracy = 0
> I0831 20:58:22.646553  5977 caffe.cpp:234] Batch 8, loss = 4.59047
> I0831 20:58:22.761013  5977 caffe.cpp:234] Batch 9, accuracy = 0
> I0831 20:58:22.761052  5977 caffe.cpp:234] Batch 9, loss = 4.62319
> I0831 20:58:22.877241  5977 caffe.cpp:234] Batch 10, accuracy = 0
> I0831 20:58:22.877264  5977 caffe.cpp:234] Batch 10, loss = 4.63062
> I0831 20:58:22.992969  5977 caffe.cpp:234] Batch 11, accuracy = 0
> I0831 20:58:22.992990  5977 caffe.cpp:234] Batch 11, loss = 4.63736
> I0831 20:58:23.105216  5977 caffe.cpp:234] Batch 12, accuracy = 0
> I0831 20:58:23.105239  5977 caffe.cpp:234] Batch 12, loss = 4.64331
> I0831 20:58:23.216982  5977 caffe.cpp:234] Batch 13, accuracy = 0
> I0831 20:58:23.217003  5977 caffe.cpp:234] Batch 13, loss = 4.63844
> I0831 20:58:23.328269  5977 caffe.cpp:234] Batch 14, accuracy = 0
> I0831 20:58:23.328290  5977 caffe.cpp:234] Batch 14, loss = 4.62079
> I0831 20:58:23.436784  5977 caffe.cpp:234] Batch 15, accuracy = 0
> I0831 20:58:23.436825  5977 caffe.cpp:234] Batch 15, loss = 4.59784
> I0831 20:58:23.547108  5977 caffe.cpp:234] Batch 16, accuracy = 0
> I0831 20:58:23.547130  5977 caffe.cpp:234] Batch 16, loss = 4.60577
> I0831 20:58:23.658761  5977 caffe.cpp:234] Batch 17, accuracy = 0
> I0831 20:58:23.658782  5977 caffe.cpp:234] Batch 17, loss = 4.59781
> I0831 20:58:23.770740  5977 caffe.cpp:234] Batch 18, accuracy = 0
> I0831 20:58:23.770763  5977 caffe.cpp:234] Batch 18, loss = 4.59607
> I0831 20:58:23.882455  5977 caffe.cpp:234] Batch 19, accuracy = 0
> I0831 20:58:23.882477  5977 caffe.cpp:234] Batch 19, loss = 4.60705
> I0831 20:58:23.993892  5977 caffe.cpp:234] Batch 20, accuracy = 0
> I0831 20:58:23.993913  5977 caffe.cpp:234] Batch 20, loss = 4.60775
> I0831 20:58:24.102294  5977 caffe.cpp:234] Batch 21, accuracy = 0
> I0831 20:58:24.102314  5977 caffe.cpp:234] Batch 21, loss = 4.59202
> I0831 20:58:24.209605  5977 caffe.cpp:234] Batch 22, accuracy = 0
> I0831 20:58:24.209630  5977 caffe.cpp:234] Batch 22, loss = 4.60682
> I0831 20:58:24.318430  5977 caffe.cpp:234] Batch 23, accuracy = 0
> I0831 20:58:24.318454  5977 caffe.cpp:234] Batch 23, loss = 4.62756
> I0831 20:58:24.424371  5977 caffe.cpp:234] Batch 24, accuracy = 0
> I0831 20:58:24.424392  5977 caffe.cpp:234] Batch 24, loss = 4.61974
> I0831 20:58:24.530743  5977 caffe.cpp:234] Batch 25, accuracy = 0
> I0831 20:58:24.530766  5977 caffe.cpp:234] Batch 25, loss = 4.62237
> I0831 20:58:24.637039  5977 caffe.cpp:234] Batch 26, accuracy = 0
> I0831 20:58:24.637059  5977 caffe.cpp:234] Batch 26, loss = 4.6219
> I0831 20:58:24.744755  5977 caffe.cpp:234] Batch 27, accuracy = 0
> I0831 20:58:24.744776  5977 caffe.cpp:234] Batch 27, loss = 4.6247
> I0831 20:58:24.852677  5977 caffe.cpp:234] Batch 28, accuracy = 0
> I0831 20:58:24.852699  5977 caffe.cpp:234] Batch 28, loss = 4.61173
> I0831 20:58:24.960541  5977 caffe.cpp:234] Batch 29, accuracy = 0
> I0831 20:58:24.960561  5977 caffe.cpp:234] Batch 29, loss = 4.6213
> I0831 20:58:25.068442  5977 caffe.cpp:234] Batch 30, accuracy = 0
> I0831 20:58:25.068462  5977 caffe.cpp:234] Batch 30, loss = 4.60979
> I0831 20:58:25.175941  5977 caffe.cpp:234] Batch 31, accuracy = 0
> I0831 20:58:25.175961  5977 caffe.cpp:234] Batch 31, loss = 4.60837
> I0831 20:58:25.282083  5977 caffe.cpp:234] Batch 32, accuracy = 0
> I0831 20:58:25.282104  5977 caffe.cpp:234] Batch 32, loss = 4.61826
> I0831 20:58:25.388100  5977 caffe.cpp:234] Batch 33, accuracy = 0
> I0831 20:58:25.388120  5977 caffe.cpp:234] Batch 33, loss = 4.61304
> I0831 20:58:25.494299  5977 caffe.cpp:234] Batch 34, accuracy = 0
> I0831 20:58:25.494320  5977 caffe.cpp:234] Batch 34, loss = 4.60632
> I0831 20:58:25.600524  5977 caffe.cpp:234] Batch 35, accuracy = 0
> I0831 20:58:25.600544  5977 caffe.cpp:234] Batch 35, loss = 4.60945
> I0831 20:58:25.706799  5977 caffe.cpp:234] Batch 36, accuracy = 0
> I0831 20:58:25.706820  5977 caffe.cpp:234] Batch 36, loss = 4.6146
> I0831 20:58:25.812988  5977 caffe.cpp:234] Batch 37, accuracy = 0
> I0831 20:58:25.813009  5977 caffe.cpp:234] Batch 37, loss = 4.63083
> I0831 20:58:25.919095  5977 caffe.cpp:234] Batch 38, accuracy = 0
> I0831 20:58:25.919114  5977 caffe.cpp:234] Batch 38, loss = 4.58947
> I0831 20:58:26.025218  5977 caffe.cpp:234] Batch 39, accuracy = 0
> I0831 20:58:26.025239  5977 caffe.cpp:234] Batch 39, loss = 4.60846
> I0831 20:58:26.133335  5977 caffe.cpp:234] Batch 40, accuracy = 0
> I0831 20:58:26.133358  5977 caffe.cpp:234] Batch 40, loss = 4.61726
> I0831 20:58:26.241446  5977 caffe.cpp:234] Batch 41, accuracy = 0
> I0831 20:58:26.241468  5977 caffe.cpp:234] Batch 41, loss = 4.60415
> I0831 20:58:26.349599  5977 caffe.cpp:234] Batch 42, accuracy = 0
> I0831 20:58:26.349620  5977 caffe.cpp:234] Batch 42, loss = 4.62642
> I0831 20:58:26.457484  5977 caffe.cpp:234] Batch 43, accuracy = 0
> I0831 20:58:26.457504  5977 caffe.cpp:234] Batch 43, loss = 4.61726
> I0831 20:58:26.565490  5977 caffe.cpp:234] Batch 44, accuracy = 0
> I0831 20:58:26.565513  5977 caffe.cpp:234] Batch 44, loss = 4.62254
> I0831 20:58:26.674124  5977 caffe.cpp:234] Batch 45, accuracy = 0
> I0831 20:58:26.674144  5977 caffe.cpp:234] Batch 45, loss = 4.61613
> I0831 20:58:26.781986  5977 caffe.cpp:234] Batch 46, accuracy = 0
> I0831 20:58:26.782007  5977 caffe.cpp:234] Batch 46, loss = 4.62502
> I0831 20:58:26.888824  5977 caffe.cpp:234] Batch 47, accuracy = 0
> I0831 20:58:26.888845  5977 caffe.cpp:234] Batch 47, loss = 4.58574
> I0831 20:58:26.995069  5977 caffe.cpp:234] Batch 48, accuracy = 0
> I0831 20:58:26.995091  5977 caffe.cpp:234] Batch 48, loss = 4.60927
> I0831 20:58:27.101228  5977 caffe.cpp:234] Batch 49, accuracy = 0.2
> I0831 20:58:27.101250  5977 caffe.cpp:234] Batch 49, loss = 4.60648
> I0831 20:58:27.101258  5977 caffe.cpp:239] Loss: 4.60677
> I0831 20:58:27.101277  5977 caffe.cpp:251] accuracy = 0.008
> I0831 20:58:27.101294  5977 caffe.cpp:251] loss = 4.60677 (\* 1 = 4.60677 loss)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/7.

## 

Limin Wang
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by kli-casia** [comment]
@wanglimin , Thank you very much.
This really helped me!  I struggled for a long time...

**Comment by kli-casia** [comment]
Hi, @wanglimin  I think you should update `vgg_16_flow_train_val_fast.prototxt`, not `vgg_16_rgb_train_val_fast.prototxt`.
Because in `cuhk_action_spatial_vgg_16_deploy.prototxt` the layer is `fc8-1`
In `cuhk_action_temporal_vgg_16_flow_deploy.prototxt` the layer is `fc8`

**Comment by wanglimin** [comment]
I see. Thanks.

Limin

On Tue, Sep 1, 2015 at 2:02 PM, Kai Li notifications@github.com wrote:

> Hi, @wanglimin https://github.com/wanglimin I think you should update
> vgg_16_flow_train_val_fast.prototxt, not
> vgg_16_rgb_train_val_fast.prototxt.
> Because in cuhk_action_spatial_vgg_16_deploy.prototxt the layer is fc8-1
> In cuhk_action_temporal_vgg_16_flow_deploy.prototxt the layer is fc8
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/7#issuecomment-136594985.

## 

Limin Wang
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/

**Comment by kli-casia** [comment]
By the way, I think the spatial and temporal pretrained model both have a fc8 layer with 1000 output.
When finetuning, just change the last layer to fc8-1 with 101 output.
I don't know why the caffemodel your provided one has fc8, the other has fc8-1 layer.
In my opinion, try to make them the same, should be more clear.^_^

**Comment by wanglimin** [comment]
Yes, it is better to be consistent with both spatial and temporal models.

Limin

On Tue, Sep 1, 2015 at 2:30 PM, Kai Li notifications@github.com wrote:

> By the way, I think the spatial and temporal pretrained model both have a
> fc8 layer with 1000 output.
> When finetuning, just change the last layer to fc8-1 with 101 output.
> I don't know why the caffemodel your provided one has fc8, the other has
> fc8-1 layer.
> In my opinion, try to make them the same, should be more clear.^_^
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/7#issuecomment-136598916.

## 

Limin Wang
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/
