### ISSUE TITLE
More infomation about the new length parameter

### ISSUE THREAD

**Issue by tonmoy-saikia** [yjxiong/caffe#72]
Hi @yjxiong as per my understanding the video data layer takes a stack of frames and passes them as blobs. However, I don't understand the meaning behind `new_length` video parameter. What is it used for?

**Comment by yjxiong** [comment]
It specifies the depth of your frame stacks. For example, in the two-stream CNN paper, the temporal net takes a stack of 10 optical flow frames (one frame contains two channels: x and y). So we set `new_length` to 10 in this case.
