### ISSUE TITLE
train_action_recognition_rgb.sh run problem

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#73]
hi !
@yjxiong @wanglimin 
感谢分享！
我用：https://github.com/yjxiong/dense_flow工具产生RGB图片，图片名称：img_0001、img_0002......
在运行：train_action_recognition_rgb.sh出下面提示：

I0502 14:31:25.172659  3781 layer_factory.hpp:74] Creating layer data
I0502 14:31:25.172678  3781 net.cpp:113] Creating Layer data
I0502 14:31:25.172686  3781 net.cpp:432] data -> data
I0502 14:31:25.172706  3781 net.cpp:432] data -> label_local
I0502 14:31:25.172714  3781 net.cpp:177] Setting up data
I0502 14:31:25.173044  3781 video_data_layer.cpp:34] Opening file: examples/action_recognition/dataset_file_examples/train_rgb_split1.txt
I0502 14:31:25.176734  3781 video_data_layer.cpp:50] A total of 9537 videos.
E0502 14:31:25.176775  3781 io.cpp:320] Could not load file ucf101_rgb_img/WallPushups/v_WallPushups_g21_c06
F0502 14:31:25.176849  3781 video_data_layer.cpp:66] Check failed: ReadSegmentRGBToDatum(lines_[lines_id_].first, lines_[lines_id_].second, offsets, new_height, new_width, new_length, &datum, true) 
**\* Check failure stack trace: ***
    @     0x7fd88da01daa  (unknown)
    @     0x7fd88da01ce4  (unknown)
    @     0x7fd88da016e6  (unknown)
    @     0x7fd88da04687  (unknown)
    @     0x7fd88de72901  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7fd88de81999  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fd88ddd6153  caffe::Net<>::Init()
    @     0x7fd88ddd7f83  caffe::Net<>::Net()
    @     0x7fd88ddf7c70  caffe::Solver<>::InitTrainNet()
    @     0x7fd88ddf8c53  caffe::Solver<>::Init()
    @     0x7fd88ddf8e26  caffe::Solver<>::Solver()
    @           0x40daa0  caffe::GetSolver<>()
    @           0x407559  train()
    @           0x405a56  main
    @     0x7fd88c9afec5  (unknown)
    @           0x40603b  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

这是什么原因呢？

**Comment by yjxiong** [comment]
The repo you used is using a different naming convention on generated images. We always recommend using the original repo

https://github.com/wanglimin/dense_flow

to generate the rgb/flow frames.

Now that you have got the frames, to save time, you can try add `name_pattern: "img_%04d.jpg"` in `video_data_param` to force using the new naming convention.
