### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by mkhademi** [yjxiong/caffe#74]
Could you please share the commands I should use to do classification for both temporal and spatial nets using the pre-trained models?

For instance, I have the following command for split1-spatial net but it gives me error:

-./build/examples/cpp_classification/classification.bin
models/action_recognition/cuhk_action_spatial_vgg_16_deploy.prototxt
models/action_recognition/cuhk_action_spatial_vgg_16_split1.caffemodel 
data/ilsvrc12/imagenet_mean.binaryproto
data/ilsvrc12/synset_words.txt
examples/action_recognition/dataset_file_examples/val_rgb_split1.txt

I think I am wrong with some of the parameters above. Please share a sample command to do classification for both temporal and spatial nets.

Thanks!

**Comment by wanglimin** [comment]
@mkhademi 

We provide a matlab script to show how to use our models of temporal and spatial nets:

https://github.com/yjxiong/caffe/blob/action_recog/action_matlab/demo.m

Limin

**Comment by mkhademi** [comment]
Thanks a lot @wanglimin for your prompt answer!
