### ISSUE TITLE
running demo.py

### ISSUE THREAD

**Issue by mkhademi** [yjxiong/caffe#75]
Hi! @wanglimin @yjxiong

When I run the action_python\demo.py script , I get the following error:

File "/home/.../caffe/action_python/VideoTemporalPrediction.py", line 85, in VideoTemporalPrediction
prediction[:, span] = np.transpose(output[feature_layer])
KeyError: 'fc8-2'

I do not see a fc8-2 layer in prototxt file. There is a fc8-1 layer in temporal and fc8 layer in spatial prototxt files!

Any idea what causes this error?

Thank you!

**Comment by yjxiong** [comment]
Hi @mkhademi ,

The python demo is contributed by community. Maybe there are some name differences. Please use the name of the classifier output, i.e. `fc8-1`, if you are using the provided models.

**Comment by mkhademi** [comment]
Thanks @yjxiong for your reply! I renamed the layers to fc8 in both temporal and spatial prototxt files for consistency. Also modified the feature_layer parameter in demo.py to fc8 and the error was resolved!

**Comment by yjxiong** [comment]
Great. Closing the issue.
