### ISSUE TITLE
fusion method problem

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#77]
hi！
@yjxiong  @wanglimin 你们好！感谢分享！

论文“Towards Good Practices for Very Deep Two-Stream ConvNets”中，分别给出了Spatial steam 和tempral net 以及fusion的识别率，文中说明是按“THUMOS13 challenge”评价方法，我理解的是根据Softmax输出结果：top1是否为对应groundtruth的class_label，来统计单个行为识别的个数，先计算分别单个行为识别率，再计算101种行为的识别率的平均值作为最终的结果，不知是否正确？

再次感谢！

**Comment by wanglimin** [comment]
@Jangol ,你的理解完全正确。

Limin

**Comment by Jangol** [comment]
@wanglimin 
谢谢你的及时回复！
