### ISSUE TITLE
The new_length for rgb_images?

### ISSUE THREAD

**Issue by liu09114** [yjxiong/caffe#79]
@wanglimin @yjxiong 
你好，我想问下，在训练rgb图片的网络中，即vgg_16_rgb_train_val_fast.prototxt中，new_length设置为1，这个参数能修改么？

我改成5，会报错，如下
I0520 09:59:47.131762 71695 net.cpp:177] Setting up conv5_3
    @     0x7f6cd5ecf2f9  caffe::VideoDataLayer<>::InternalThreadEntry()
    @     0x7f6cd596924a  (unknown)
    @     0x7f6cd5747dc5  start_thread
    @     0x7f6cbed5928d  __clone
Aborted (core dumped)

**Comment by yjxiong** [comment]
可以。但需要保证每个video帧数大于`new_length`

**Comment by liu09114** [comment]
@yjxiong @wanglimin 
那我报错的原因是什么呢？
还有一个问题，如果修改了new_length，要使用预训练的方法的话，第一层的权重要怎么修改？还是用随机初始化的方法来修改？
