### ISSUE TITLE
Classification problem

### ISSUE THREAD

**Issue by mkhademi** [yjxiong/caffe#81]
Hi @wanglimin @yjxiong ,

When I try to classify a single video (e.g. a sample video from training set), I get the highest confidence score for a totally wrong class. I already tried for multiple videos and none of them was classified correctly! Do you use the same index labels as the following? http://crcv.ucf.edu/THUMOS14/Class%20Index.txt

If so, can you think of anything that could cause this problem?
Your results are based on top-1 class predictions, right?

Thanks!

**Comment by yjxiong** [comment]
I think we are using the same label list.

Some common problems could be incorrect names of the classifier layer and its output.

**Comment by mkhademi** [comment]
@yjxiong @chuckcho In my demo.py file, I am using feature_layer = "fc8" and num_categories = 101. I already checked my cuhk_action_spatial_vgg_16_deploy.prototxt and cuhk_action_temporal_vgg_16_deploy.prototx files. They both end with fc8.

Is there any other layer name that I need to check?

**Comment by wanglimin** [comment]
please use our released proto:

https://github.com/yjxiong/caffe/blob/action_recog/models/action_recognition/cuhk_action_spatial_vgg_16_deploy.prototxt#L332

It should be fc8-1.

limin

**Comment by mkhademi** [comment]
@wanglimin I am actually using your proto file. The thing is you have fc8-1 in spatial prototxt file and fc8 layer as the last layer in temporal prototxt file. I renamed fc8-1 to fc8 in spatial prototxt file so the name of last layer in the two nets be consistent. Also in demo.py file, there is only one feature_layer parameter that is passed to both VideoSpatial and VideoTemporal functions. Therefore, I figured out the last layers of the two networks should have the same name otherwise the code gives error.

**Comment by wanglimin** [comment]
@mkhademi 

First of all, you cannot modify the proto files. Otherwise, the modified layer will be initialized randomly. So the prediction results are not correct. Then, you can define two layer names for spatial and temporal nets in demo.py. Actually spatial and temporal net do not the share the same last layer.

Limin

**Comment by mkhademi** [comment]
@wanglimin Thank you so much for your response! The problem is solved!

**Comment by yjxiong** [comment]
Closing this issue as it's marked solved.
