### ISSUE TITLE
(segmentation fault) error - running MPI

### ISSUE THREAD

**Issue by romanbogza** [yjxiong/caffe#83]
Hey,

I am running into a segmentation Fault error when attempting to train using "mpirun np -4  caffe <solver> <weights>" command. I am using MPI version 1.8, CUDA 7.5, cuDNN v5. Do you happen to know what the issue might be? 

Can you also provide your system configuration?

Thanks,
Roman

Below is my complete error:

`I0613 20:30:47.435468 68597 solver.cpp:336] Model Synchronization Communication time 0.193417 second
**\* Aborted at 1465849847 (unix time) try "date -d @1465849847" if you are using GNU date ***
PC: @     0x7f54b5f57ee0 (unknown)
**\* SIGSEGV (@0x2706fe8000) received by PID 68598 (TID 0x7f543c907700) from PID 117342208; stack trace: ***
    @     0x7f54b5ef6cb0 (unknown)
    @     0x7f54b5f57ee0 (unknown)
    @     0x7f54b689e779 (unknown)
    @     0x7f548fa9685d (unknown)
    @     0x7f5490900c9c (unknown)
    @     0x7f54908f356c (unknown)
    @     0x7f548ebd32e7 (unknown)
    @     0x7f548ebd96ef (unknown)
    @     0x7f54b68040c9 (unknown)
    @     0x7f54b72ae0de caffe::MPIComm::DispatchJob()
    @     0x7f54b72ae38c caffe::MPIComm::ThreadFunc()
    @     0x7f54b5ab1a4a (unknown)
    @     0x7f54b5890184 start_thread
    @     0x7f54b5fba37d (unknown)
    @                0x0 (unknown)
**\* Aborted at 1465849847 (unix time) try "date -d @1465849847" if you are using GNU date ***
PC: @     0x7f1422e2fee0 (unknown)
**\* SIGSEGV (@0x2706fe8000) received by PID 68597 (TID 0x7f13a96f1700) from PID 117342208; stack trace: ***
    @     0x7f1422dcecb0 (unknown)
    @     0x7f1422e2fee0 (unknown)
    @     0x7f1423776779 (unknown)
    @     0x7f13fc96e85d (unknown)
    @     0x7f13fd7d8c9c (unknown)
    @     0x7f13fd7cb56c (unknown)
    @     0x7f13fbaab2e7 (unknown)
    @     0x7f13fbab16ef (unknown)
    @     0x7f14236dc0c9 (unknown)
    @     0x7f14241860de caffe::MPIComm::DispatchJob()
    @     0x7f142418638c caffe::MPIComm::ThreadFunc()
    @     0x7f1422989a4a (unknown)
    @     0x7f1422768184 start_thread
    @     0x7f1422e9237d (unknown)
    @                0x0 (unknown)

mpirun noticed that process rank 1 with PID 68598 on node ip-172-31-52-35 exited on signal 11 (Segmentation fault**).`

```
```

**Comment by yjxiong** [comment]
Cannot tell what's going on based your decription. Would you please provide more details? 
Also, please make sure the mpirun executable is from the OpenMPI version you build the code.
And please check whether the MPI is compiled with `--with-cuda` option.
