### ISSUE TITLE
Code for your CVPR16 papers

### ISSUE THREAD

**Issue by zhangshushu15** [yjxiong/caffe#87]
Hi,

Does this repo have code for your CVPR16 papers? 

"Real-time Action Recognition with Enhanced Motion Vector CNNs"
and
"Actionness Estimation Using Hybrid Fully Convolutional Networks"

Thanks.

**Comment by yjxiong** [comment]
Yes.

The repo is the caffe modification used for training. We will add the links to testing code and models very soon.

**Comment by zhangshushu15** [comment]
Thanks, yj. Let me look into your training code.

**Comment by zhangshushu15** [comment]
Hi yjxiong,

I looked into the code but only found training code for the paper "Toward good practices for very deep two-stream ConvNets". Can you point me to the part for the two papers mentioned above?

Thanks!
Shu

**Comment by yjxiong** [comment]
Hi,

This is the codebase for the network training. I will link the project homepage of the two papers once ready. Then you can find more details and model download on them.

Please stay tuned.

**Comment by zhangshushu15** [comment]
Great. I look forward to the details. Thanks!

Shu

**Comment by yjxiong** [comment]
Hi @zhangshushu15 ,

The links to the code releases of the two papers have been added to the repo README. 
Please see them in the "working examples" section.

**Comment by zhangshushu15** [comment]
Thank you, yjxiong. I'll take a look!
