### ISSUE TITLE
training data path

### ISSUE THREAD

**Issue by jiaxinwoo** [yjxiong/caffe#88]
Hello,
  Anybody know where should I put the data?
  I want to train the two stream network on UCF.  But I can't figure out what the real path
  of  train_rgb_split1.txt  such as 
  ucf101_rgb_img/FieldHockeyPenalty/v_FieldHockeyPenalty_g02_c01  is?
  I put the whole ucf101_rgb_img file under caffe root. But it sends an error "Could not load file    ucf101_rgb_img/WallPushups/v_WallPushups_g21_c06" when I   execute "./examples/action_recognition/train_action_recognition_rgb.sh"
  Anybody know ?

**Comment by yjxiong** [comment]
Paths in the list file, like

`ucf101_rgb_img/FieldHockeyPenalty/v_FieldHockeyPenalty_g02_c01`

are the paths to the directories containing the extracted frames or the optical flow images.

Issue an `ls` with one path you should be able to see the images.

**Comment by jiaxinwoo** [comment]
thanks @yjxiong 
I had figured out this problem. I had a wrong image file name.
thanks again

**Comment by yjxiong** [comment]
Good to know. And enjoy.
