### ISSUE TITLE
Cannot import caffe (PyCaffe)

### ISSUE THREAD

**Issue by EvanWeiner** [yjxiong/caffe#89]
What version of Python is permitted? After make and set python layers on, when I import caffe, I get an error:

ImportError: ../python/caffe/_caffe.so: undefined symbol: _ZN5...

**Comment by yjxiong** [comment]
We use Python2.7.

Your problem seems to be caused by linking and running with different versions of libraries.

**Comment by EvanWeiner** [comment]
I also use Python2.7.

My problem is I am compiling with make, instead of the cmake method. You wrote earlier that make is not supported officially by you and team. I need to use make because the output of cmake does not contain everything I need. Do you now or in future support officially the make method (e.g. using Makefile.config)?

**Comment by yjxiong** [comment]
Sorry, we do not plan to do any  test on the Makefile.config in near future. Some users report they managed to compile the code with it by manually setting the dependencies.

Also, you are welcome to contribute your solutions if convenient:)

**Comment by EvanWeiner** [comment]
Something is not right when using Makefile.config (if can make it work I am happy to share). So I tried again to use cmake official method. The problem is that PyCaffe seems not fully compiled when using cmake.  I checked the install manifest, here's the only things I get after cmake:

/build/install/lib/libcaffe.so
/build/install/lib/libproto.a
/build/install/python/caffe/proto/caffe_pb2.py
/build/install/python/caffe/proto/**init**.py

There is no _caffe.so -- which I get when using make with regular caffe repos. Without _caffe.so, it's broken for me. Any hints how to get the compiled _caffe.so?

**Comment by yjxiong** [comment]
In the output of `cmake` command, you should see 

```
-- Found the following Boost libraries:
--   python
```

and

```
-- Python:
--   Interpreter       :   /opt/anaconda/bin/python2.7 (ver. 2.7.11)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
--   NumPy             :   /opt/anaconda/lib/python2.7/site-packages/numpy/core/include (ver 1.11.0)
```

These indicate the CMake is able to build the Python wrapper. Otherwise, it will skip the Python wrapper compilation.

So if you cannot see the first one, it means your boost version is lower than 1.55. Please update it then.
If it is the second one, please make sure your Python installation has Numpy.

**Comment by EvanWeiner** [comment]
Cool, I feel like we're making progress now. The output of my cmake is:

-- Could NOT find Boost
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)

## -- Python interface is disabled or not all required dependecies found. Building without it...

-- ******************\* Caffe Configuration Summary *******************
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   v0.9999-1553-gc54adf0
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized

## --   Build type        :   Release

--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON

## --   CPU_ONLY          :   OFF

-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   Snappy            :   Yes (ver. 1.1.0)
--   LevelDB           :   Yes (ver. 1.15)
--   OpenCV            :   Yes (ver. 2.4.8)

## --   CUDA              :   Yes (ver. 7.5)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52
--   cuDNN             :   Yes

**Comment by EvanWeiner** [comment]
FYI the current boost library on Ubuntu "Trusty" is 1.54 (http://packages.ubuntu.com/trusty/libboost-all-dev). It seems not easy to install a later version.

**Comment by yjxiong** [comment]
It is in the apt. But it is named libboost1.55-all-dev. You can first
remove libboost and then install it.

On Wednesday, July 13, 2016, EvanWeiner notifications@github.com wrote:

> FYI the current boost library on Ubuntu "Trusty" is 1.54 (
> http://packages.ubuntu.com/trusty/libboost-all-dev). It seems not easy to
> install a later version.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/yjxiong/caffe/issues/89#issuecomment-232241583, or mute
> the thread
> https://github.com/notifications/unsubscribe/AGg4d6De_Vx7f6QAQPFKTs3Uz1_i_88qks5qVFTNgaJpZM4JKGNm
> .

## 

熊元骏
Xiong, Yuanjun

Department of Information Engineering,
The Chinese University of Hong Kong.

E-mail: bitxiong@gmail.com
Mobile: +852 54282253
Mainland China Mobile: +86 147 1430 8814
Address: SHB703, The Chinese University of Hong Kong.
              Shatin, N.T, Hong Kong.

**Comment by EvanWeiner** [comment]
You are so nice! This worked!
