### ISSUE TITLE
Why conv layers having bias term even before batch norm?

### ISSUE THREAD

**Issue by shiyemin** [yjxiong/caffe#98]
Normally, the ops before batch norm just multiply its weights and add bias term in batch norm. But in your prototxt, all conv layers have its own bias term and batch norm layers have another bias.

Though, i also find that the bias term in conv layer never changed. Is there any code to stop the learning of bias term?

**Comment by yjxiong** [comment]
Which `prototxt` do you refer to? Generally, the bias term in a convolution layer will not function if BN is applied and can thus be turned off. In Caffe, you can easily do this by setting `bias_term: false` in any `convolution_param`.  

Removing the bias term from convolution layers is OK for architectures with BN, but not OK for earlier models like VGG/AlexNet. So in Caffe people usually use the aforementioned option to switch on/off the bias term.

Hope these clear your concerns.

**Comment by shiyemin** [comment]
I'm reading the prototxt of your TSN https://github.com/yjxiong/temporal-segment-networks where all conv layers have bias.

**Comment by yjxiong** [comment]
We didn't turn off the bias term because it does not affect training. If you do feel uncomfortable with it. You can simply set `bias_term: false` for convolution layers.

**Comment by shiyemin** [comment]
OK, thanks very much!

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
